load(":toolchains.bzl", "register_cc_toolchain")

exports_files(["unikernel.ld", "unikernel_arm64.ld", "unikernel_limine.ld"])

filegroup(name = "empty")
filegroup(name = "all_files", srcs = glob(["**"]))

register_cc_toolchain(name = "unikernel_cc_toolchain_x86_64",  arch = "x86_64",        cpu = "x86_64",  os = "none")
register_cc_toolchain(name = "unikernel_cc_toolchain_aarch64",  arch = "aarch64",       cpu = "aarch64", os = "none")
register_cc_toolchain(name = "cc_toolchain_aarch64_macos",      arch = "aarch64_macos", cpu = "aarch64", os = "macos")
register_cc_toolchain(name = "cc_toolchain_x86_64_linux",       arch = "x86_64_linux",  cpu = "x86_64",  os = "linux")
