// tools/hvf-runner/src/userspace_net.rs
//
// Userspace TCP/IP proxy with lock-free IO.
//
// Two threads, zero locks on the hot path:
//   IO thread:  poll() on all sockets → build frames → push to RX ring
//               drain TX ring → write() to sockets
//   vCPU thread: drain RX ring → inject into guest virtio
//                extract from guest virtio → push to TX ring
//
// Communication via two SPSC lock-free ring buffers (no Mutex).

use std::collections::VecDeque;

use crate::hvf;
use crate::spsc::SpscRing;
use crate::virtio;

// ── Network constants ───────────────────────────────────────────────────────

const VIRTIO_NET_HDR_SIZE: usize = 12;
const GW_MAC: [u8; 6] = [0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff];
const VM_IP: [u8; 4] = [10, 0, 2, 15];
const GW_IP: [u8; 4] = [10, 0, 2, 2];
const BROADCAST_IP: [u8; 4] = [255, 255, 255, 255];

// ── Lock-free rings (shared between IO thread and vCPU thread) ──────────────

/// IO thread → vCPU thread: Ethernet frames to inject into guest RX.
static mut RX_RING: Option<SpscRing<256>> = None;
/// vCPU thread → IO thread: Ethernet frames extracted from guest TX.
static mut TX_RING: Option<SpscRing<256>> = None;
/// Pipe for vCPU → IO thread wakeup (write end). When the vCPU pushes
/// to TX_RING, it writes 1 byte here to wake the IO thread's poll().
static WAKE_WR: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(-1);
/// Read end of the wake pipe — included in the IO thread's poll() set.
static WAKE_RD: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(-1);

// ── Per-connection state (IO thread only) ───────────────────────────────────

struct ProxyConn {
    host_fd: i32,
    src_port: u16,
    my_seq: u32,
    peer_ack: u32,
    state: u8, // 0=SYN_SENT, 1=ESTABLISHED, 2=CLOSED
    pending: Vec<u8>,
}

// ── IO thread state ─────────────────────────────────────────────────────────

struct IoState {
    listen_fd: i32,
    conns: Vec<ProxyConn>,
    next_port: u16,
    guest_mac: [u8; 6],
    read_buf: [u8; 8192],
    // Frames generated by handle_guest_tx that need injection (ARP/TCP replies).
    // Pushed to RX_RING at the end of each poll iteration.
    reply_queue: VecDeque<Vec<u8>>,
}

// ── Public API (called from main thread and vCPU thread) ────────────────────

/// Start userspace networking. Spawns the IO thread. Returns guest MAC.
pub fn start(port: u16) -> Result<[u8; 6], String> {
    let mac: [u8; 6] = [0x52, 0x54, 0x00, 0x12, 0x34, 0x56];

    // Create listen socket.
    let listen_fd = unsafe {
        let fd = libc::socket(libc::AF_INET, libc::SOCK_STREAM, 0);
        if fd < 0 { return Err("socket() failed".into()); }
        let one: i32 = 1;
        libc::setsockopt(fd, libc::SOL_SOCKET, libc::SO_REUSEADDR,
                         &one as *const _ as *const _, 4);
        let mut addr: libc::sockaddr_in = std::mem::zeroed();
        addr.sin_family = libc::AF_INET as u8;
        addr.sin_port = port.to_be();
        addr.sin_addr.s_addr = u32::from_be_bytes([127, 0, 0, 1]).to_be();
        if libc::bind(fd, &addr as *const _ as *const _, std::mem::size_of_val(&addr) as u32) < 0 {
            let e = std::io::Error::last_os_error();
            libc::close(fd);
            return Err(format!("bind({port}): {e}"));
        }
        libc::listen(fd, 128);
        libc::fcntl(fd, libc::F_SETFL, libc::O_NONBLOCK);
        fd
    };

    // Allocate rings and wake pipe.
    unsafe {
        RX_RING = Some(SpscRing::new());
        TX_RING = Some(SpscRing::new());
        let mut fds = [0i32; 2];
        libc::pipe(fds.as_mut_ptr());
        libc::fcntl(fds[0], libc::F_SETFL, libc::O_NONBLOCK);
        libc::fcntl(fds[1], libc::F_SETFL, libc::O_NONBLOCK);
        WAKE_RD.store(fds[0], std::sync::atomic::Ordering::Relaxed);
        WAKE_WR.store(fds[1], std::sync::atomic::Ordering::Relaxed);
    }

    // Send gratuitous ARP so the guest learns gateway MAC at boot.
    let grat_arp = build_grat_arp(&mac);
    unsafe { RX_RING.as_ref().unwrap().push(&grat_arp); }

    // Spawn IO thread.
    std::thread::spawn(move || {
        io_thread(listen_fd, mac);
    });

    eprintln!();
    eprintln!("  VM network: 10.0.2.15 (userspace, lock-free)");
    eprintln!("  Benchmark:  wrk -t1 -c1 -d10s http://localhost:{port}/health");
    eprintln!();

    Ok(mac)
}

/// Inject buffered RX frames into guest virtio ring.
/// Called from the virtio INTERRUPT_STATUS read (guest polls).
/// vCPU thread only — zero syscalls, just memory copies.
pub fn flush_rx_into(dev: &mut virtio::VirtioNet) {
    let ring = unsafe { match RX_RING.as_ref() { Some(r) => r, None => return } };

    if ring.is_empty() { return; }

    static RX_LAST: std::sync::atomic::AtomicU16 = std::sync::atomic::AtomicU16::new(0);

    let q = dev.queue(0);
    if !q.ready { return; }
    let desc_base = q.desc_addr();
    let avail_base = q.avail_addr();
    let used_base = q.used_addr();
    let qsize = q.num as u16;
    if qsize == 0 { return; }

    let mut injected = 0u32;
    while ring.pop(|frame| {
        let avail_idx = unsafe {
            core::ptr::read_volatile(dev.gpa_to_host(avail_base + 2) as *const u16)
        };
        let last = RX_LAST.load(std::sync::atomic::Ordering::Relaxed);
        if last == avail_idx { return; }

        let ring_idx = last & (qsize - 1);
        let desc_idx = unsafe {
            core::ptr::read_volatile(
                dev.gpa_to_host(avail_base + 4 + ring_idx as u64 * 2) as *const u16
            )
        };
        let addr = unsafe {
            core::ptr::read_unaligned(
                dev.gpa_to_host(desc_base + desc_idx as u64 * 16) as *const u64
            )
        };
        let n = frame.len();
        unsafe {
            core::ptr::copy_nonoverlapping(frame.as_ptr(), dev.gpa_to_host(addr), n);
        }
        let used_idx = unsafe {
            core::ptr::read_volatile(dev.gpa_to_host(used_base + 2) as *const u16)
        };
        unsafe {
            let entry = dev.gpa_to_host(used_base + 4 + (used_idx & (qsize - 1)) as u64 * 8);
            core::ptr::write_unaligned(entry as *mut u32, desc_idx as u32);
            core::ptr::write_unaligned(entry.add(4) as *mut u32, n as u32);
            core::ptr::write_volatile(
                dev.gpa_to_host(used_base + 2) as *mut u16,
                used_idx.wrapping_add(1),
            );
        }
        RX_LAST.store(last.wrapping_add(1), std::sync::atomic::Ordering::Relaxed);
        dev.used_idx[0] = used_idx.wrapping_add(1);
        dev.interrupt_status |= 1;
        injected += 1;
    }) {}

    if injected > 0 {
        unsafe { core::arch::asm!("dsb sy", options(nostack)); }
        unsafe { hvf::hv_gic_set_spi(35, true); }
    }
}

/// check_rx is now a no-op — the IO thread pushes to RX_RING,
/// and flush_rx_into() drains it when the guest polls.
pub fn check_rx() {
    // Nothing to do — IO thread handles socket reads.
    // flush_rx_into() is called from the INTERRUPT_STATUS MMIO read path.
}

/// Extract frames from guest TX ring and push to TX_RING.
/// vCPU thread only — zero syscalls.
pub fn process_tx() {
    let tx_ring = unsafe { match TX_RING.as_ref() { Some(r) => r, None => return } };

    let mut dev_lock = virtio::DEVICE.lock().unwrap();
    let dev = match dev_lock.as_mut() {
        Some(d) => d,
        None => return,
    };

    let q = dev.queue(1);
    if !q.ready { return; }
    let desc_base = q.desc_addr();
    let avail_base = q.avail_addr();
    let used_base = q.used_addr();
    let qsize = q.num as u16;
    if qsize == 0 { return; }

    let avail_idx = unsafe {
        core::ptr::read_volatile(dev.gpa_to_host(avail_base + 2) as *const u16)
    };
    static TX_LAST: std::sync::atomic::AtomicU16 = std::sync::atomic::AtomicU16::new(0);
    let mut last = TX_LAST.load(std::sync::atomic::Ordering::Relaxed);

    while last != avail_idx {
        let ring_idx = last & (qsize - 1);
        let desc_idx = unsafe {
            core::ptr::read_volatile(
                dev.gpa_to_host(avail_base + 4 + ring_idx as u64 * 2) as *const u16
            )
        };
        let (addr, len) = unsafe {
            let dp = dev.gpa_to_host(desc_base + desc_idx as u64 * 16);
            (core::ptr::read_unaligned(dp as *const u64),
             core::ptr::read_unaligned(dp.add(8) as *const u32) as usize)
        };

        if len > VIRTIO_NET_HDR_SIZE {
            let frame = unsafe {
                std::slice::from_raw_parts(
                    dev.gpa_to_host(addr).add(VIRTIO_NET_HDR_SIZE),
                    len - VIRTIO_NET_HDR_SIZE,
                )
            };
            tx_ring.push(frame);
        }

        let used_idx = unsafe {
            core::ptr::read_volatile(dev.gpa_to_host(used_base + 2) as *const u16)
        };
        unsafe {
            let entry = dev.gpa_to_host(used_base + 4 + (used_idx & (qsize - 1)) as u64 * 8);
            core::ptr::write_unaligned(entry as *mut u32, desc_idx as u32);
            core::ptr::write_unaligned(entry.add(4) as *mut u32, len as u32);
            core::ptr::write_volatile(
                dev.gpa_to_host(used_base + 2) as *mut u16,
                used_idx.wrapping_add(1),
            );
        }
        last = last.wrapping_add(1);
    }
    TX_LAST.store(last, std::sync::atomic::Ordering::Relaxed);

    dev.interrupt_status |= 1;
    unsafe { core::arch::asm!("dsb sy", options(nostack)); }
    drop(dev_lock);
    unsafe { hvf::hv_gic_set_spi(35, true); }

    // Wake IO thread to drain TX ring immediately.
    let wfd = WAKE_WR.load(std::sync::atomic::Ordering::Relaxed);
    if wfd >= 0 {
        unsafe { libc::write(wfd, [1u8].as_ptr() as *const _, 1); }
    }
}

// ── IO thread ───────────────────────────────────────────────────────────────

fn io_thread(listen_fd: i32, mac: [u8; 6]) {
    let rx_ring = unsafe { RX_RING.as_ref().unwrap() };
    let tx_ring = unsafe { TX_RING.as_ref().unwrap() };

    let mut io = IoState {
        listen_fd,
        conns: Vec::new(),
        next_port: 40000,
        guest_mac: mac,
        read_buf: [0u8; 8192],
        reply_queue: VecDeque::new(),
    };

    loop {
        // 1. Build pollfd array: wake pipe + listen socket + all connections.
        let wake_rd = WAKE_RD.load(std::sync::atomic::Ordering::Relaxed);
        let mut pollfds: Vec<libc::pollfd> = Vec::with_capacity(2 + io.conns.len());
        pollfds.push(libc::pollfd { fd: wake_rd, events: libc::POLLIN, revents: 0 });
        pollfds.push(libc::pollfd { fd: io.listen_fd, events: libc::POLLIN, revents: 0 });
        for c in io.conns.iter() {
            pollfds.push(libc::pollfd {
                fd: if c.host_fd >= 0 && c.state < 2 { c.host_fd } else { -1 },
                events: libc::POLLIN,
                revents: 0,
            });
        }

        // 2. poll() — block until data arrives or vCPU wakes us via pipe.
        let ready = unsafe {
            libc::poll(pollfds.as_mut_ptr(), pollfds.len() as u32, 5)
        };

        // Drain wake pipe.
        if pollfds[0].revents & libc::POLLIN != 0 {
            let mut drain = [0u8; 64];
            unsafe { libc::read(wake_rd, drain.as_mut_ptr() as *mut _, drain.len()); }
        }

        // 3. Drain TX ring: write guest responses to host sockets.
        while tx_ring.pop(|frame| {
            handle_guest_tx(frame, &mut io, rx_ring);
        }) {}

        // Push any reply frames (ARP/TCP ACKs) to the RX ring.
        while let Some(frame) = io.reply_queue.pop_front() {
            if !rx_ring.push(&frame) { break; }
        }

        if ready <= 0 { continue; }

        // 4. Accept new connections.
        if pollfds[1].revents & libc::POLLIN != 0 {
            loop {
                let client_fd = unsafe {
                    libc::accept(io.listen_fd, std::ptr::null_mut(), std::ptr::null_mut())
                };
                if client_fd < 0 { break; }
                unsafe {
                    libc::fcntl(client_fd, libc::F_SETFL, libc::O_NONBLOCK);
                    let one: i32 = 1;
                    libc::setsockopt(client_fd, libc::IPPROTO_TCP, libc::TCP_NODELAY,
                                     &one as *const _ as *const _, 4);
                }
                let src_port = io.next_port;
                io.next_port = if io.next_port >= 59999 { 40000 } else { io.next_port + 1 };

                // SYN to guest.
                let frame = build_tcp_frame(
                    &io.guest_mac, GW_IP, VM_IP,
                    src_port, 80, 1000, 0, 0x02, &[],
                );
                rx_ring.push(&frame);

                io.conns.push(ProxyConn {
                    host_fd: client_fd, src_port, my_seq: 1001, peer_ack: 0,
                    state: 0, pending: Vec::new(),
                });
            }
        }

        // 5. Read from connections reported ready by poll().
        for i in 0..io.conns.len() {
            if i + 2 >= pollfds.len() { break; }
            if pollfds[i + 2].revents & (libc::POLLIN | libc::POLLHUP) == 0 { continue; }
            read_one_socket(&mut io, i, rx_ring);
        }

        // 6. If we pushed any frames to the RX ring, assert SPI 35
        // to wake the vCPU from WFI. Without this, the guest sleeps
        // ~215µs in hv_vcpu_run() before waking up to poll.
        if !rx_ring.is_empty() {
            unsafe { crate::hvf::hv_gic_set_spi(35, true); }
        }
    }
}

/// Non-blocking read from ALL active sockets. Called after TX drain
/// to pick up wrk's next requests without a second poll() syscall.
fn read_all_sockets(io: &mut IoState, rx_ring: &SpscRing<256>) {
    for i in 0..io.conns.len() {
        read_one_socket(io, i, rx_ring);
    }
}

/// Non-blocking read from one socket.
fn read_one_socket(io: &mut IoState, i: usize, rx_ring: &SpscRing<256>) {
    let fd = io.conns[i].host_fd;
    if fd < 0 { return; }
    let n = unsafe {
        libc::read(fd, io.read_buf.as_mut_ptr() as *mut _, io.read_buf.len())
    };
    if n == 0 {
        if io.conns[i].state == 1 {
            let mac = io.guest_mac;
            let c = &mut io.conns[i];
            let frame = build_tcp_frame(
                &mac, GW_IP, VM_IP, c.src_port, 80,
                c.my_seq, c.peer_ack, 0x11, &[],
            );
            c.my_seq = c.my_seq.wrapping_add(1);
            c.state = 2;
            rx_ring.push(&frame);
        }
    } else if n > 0 {
        let data = &io.read_buf[..n as usize];
        let mac = io.guest_mac;
        let c = &mut io.conns[i];
        if c.state == 1 {
            push_data_frames(c, data, &mac, rx_ring);
        } else {
            c.pending.extend_from_slice(data);
        }
    }
}

// ── Guest TX frame handling (IO thread) ─────────────────────────────────────

fn handle_guest_tx(frame: &[u8], io: &mut IoState, rx_ring: &SpscRing<256>) {
    if frame.len() < 14 { return; }
    let ethertype = u16::from_be_bytes([frame[12], frame[13]]);
    io.guest_mac.copy_from_slice(&frame[6..12]);

    match ethertype {
        0x0806 => handle_arp(&frame[14..], io),
        0x0800 => handle_ipv4(&frame[14..], io, rx_ring),
        _ => {}
    }
}

fn handle_arp(arp: &[u8], io: &mut IoState) {
    if arp.len() < 28 { return; }
    if u16::from_be_bytes([arp[6], arp[7]]) != 1 { return; }
    if arp[24..28] != GW_IP { return; }

    let mut reply = Vec::with_capacity(14 + 28);
    reply.extend_from_slice(&io.guest_mac);
    reply.extend_from_slice(&GW_MAC);
    reply.extend_from_slice(&0x0806u16.to_be_bytes());
    reply.extend_from_slice(&1u16.to_be_bytes());
    reply.extend_from_slice(&0x0800u16.to_be_bytes());
    reply.push(6); reply.push(4);
    reply.extend_from_slice(&2u16.to_be_bytes());
    reply.extend_from_slice(&GW_MAC);
    reply.extend_from_slice(&GW_IP);
    reply.extend_from_slice(&arp[8..14]);
    reply.extend_from_slice(&arp[14..18]);
    let mut frame = vec![0u8; VIRTIO_NET_HDR_SIZE];
    frame.extend_from_slice(&reply);
    io.reply_queue.push_back(frame);
}

fn handle_ipv4(ip: &[u8], io: &mut IoState, rx_ring: &SpscRing<256>) {
    if ip.len() < 20 { return; }
    let ihl = ((ip[0] & 0x0f) as usize) * 4;
    match ip[9] {
        6 => handle_tcp(&ip[ihl..], io, rx_ring),
        17 => handle_udp(&ip[ihl..], io),
        _ => {}
    }
}

fn handle_tcp(tcp: &[u8], io: &mut IoState, rx_ring: &SpscRing<256>) {
    if tcp.len() < 20 { return; }
    let src_port = u16::from_be_bytes([tcp[0], tcp[1]]);
    let dst_port = u16::from_be_bytes([tcp[2], tcp[3]]);
    let seq = u32::from_be_bytes([tcp[4], tcp[5], tcp[6], tcp[7]]);
    let data_offset = ((tcp[12] >> 4) as usize) * 4;
    let flags = tcp[13];
    let payload = if tcp.len() > data_offset { &tcp[data_offset..] } else { &[] };

    if flags & 0x04 != 0 {
        if let Some(idx) = io.conns.iter().position(|c| c.src_port == dst_port) {
            unsafe { libc::close(io.conns[idx].host_fd); }
            io.conns.swap_remove(idx);
        }
        return;
    }

    let mac = io.guest_mac;
    let c = match io.conns.iter_mut().find(|c| c.src_port == dst_port) {
        Some(c) => c,
        None => return,
    };

    match c.state {
        0 => {
            if flags & 0x12 == 0x12 {
                c.peer_ack = seq.wrapping_add(1);
                c.state = 1;
                let frame = build_tcp_frame(
                    &mac, GW_IP, VM_IP, c.src_port, 80,
                    c.my_seq, c.peer_ack, 0x10, &[],
                );
                io.reply_queue.push_back(frame);

                if !c.pending.is_empty() {
                    let pending = std::mem::take(&mut c.pending);
                    push_data_frames(c, &pending, &mac, rx_ring);
                }
            }
        }
        1 => {
            if !payload.is_empty() {
                c.peer_ack = seq.wrapping_add(payload.len() as u32);
                unsafe {
                    libc::write(c.host_fd, payload.as_ptr() as *const _, payload.len());
                }
                let frame = build_tcp_frame(
                    &mac, GW_IP, VM_IP, c.src_port, src_port,
                    c.my_seq, c.peer_ack, 0x10, &[],
                );
                io.reply_queue.push_back(frame);
            }
            if flags & 0x01 != 0 {
                c.peer_ack = c.peer_ack.wrapping_add(1);
                let frame = build_tcp_frame(
                    &mac, GW_IP, VM_IP, c.src_port, src_port,
                    c.my_seq, c.peer_ack, 0x11, &[],
                );
                c.my_seq = c.my_seq.wrapping_add(1);
                c.state = 2;
                io.reply_queue.push_back(frame);
                unsafe { libc::close(c.host_fd); }
                c.host_fd = -1;
            }
        }
        _ => {}
    }
}

fn handle_udp(udp: &[u8], io: &mut IoState) {
    if udp.len() < 8 { return; }
    let src_port = u16::from_be_bytes([udp[0], udp[1]]);
    let dst_port = u16::from_be_bytes([udp[2], udp[3]]);
    if src_port == 68 && dst_port == 67 {
        handle_dhcp(&udp[8..], io);
    }
}

fn handle_dhcp(bootp: &[u8], io: &mut IoState) {
    if bootp.len() < 240 { return; }
    let mut msg_type: u8 = 0;
    let mut i = 240;
    while i < bootp.len() {
        let opt = bootp[i];
        if opt == 255 { break; }
        if opt == 0 { i += 1; continue; }
        if i + 1 >= bootp.len() { break; }
        let len = bootp[i + 1] as usize;
        if i + 2 + len > bootp.len() { break; }
        if opt == 53 && len >= 1 { msg_type = bootp[i + 2]; }
        i += 2 + len;
    }
    if msg_type != 1 && msg_type != 3 { return; }
    let reply_type: u8 = if msg_type == 1 { 2 } else { 5 };

    let mut pkt = Vec::with_capacity(400);
    pkt.extend_from_slice(&[0xff; 6]);
    pkt.extend_from_slice(&GW_MAC);
    pkt.extend_from_slice(&0x0800u16.to_be_bytes());
    let ip_start = pkt.len();
    pkt.extend_from_slice(&[0u8; 20]);
    let udp_start = pkt.len();
    pkt.extend_from_slice(&[0u8; 8]);
    let bp_start = pkt.len();
    pkt.resize(bp_start + 236, 0);
    pkt[bp_start] = 2;
    pkt[bp_start + 1] = 1; pkt[bp_start + 2] = 6;
    pkt[bp_start + 4..bp_start + 8].copy_from_slice(&bootp[4..8]);
    pkt[bp_start + 16..bp_start + 20].copy_from_slice(&VM_IP);
    pkt[bp_start + 20..bp_start + 24].copy_from_slice(&GW_IP);
    pkt[bp_start + 28..bp_start + 34].copy_from_slice(&io.guest_mac);
    pkt.extend_from_slice(&[99, 130, 83, 99]);
    pkt.extend_from_slice(&[53, 1, reply_type]);
    pkt.extend_from_slice(&[54, 4]); pkt.extend_from_slice(&GW_IP);
    pkt.extend_from_slice(&[51, 4, 0, 1, 0x51, 0x80]);
    pkt.extend_from_slice(&[1, 4, 255, 255, 255, 0]);
    pkt.extend_from_slice(&[3, 4]); pkt.extend_from_slice(&GW_IP);
    pkt.extend_from_slice(&[6, 4, 10, 0, 2, 3]);
    pkt.push(255);

    let udp_len = (pkt.len() - udp_start) as u16;
    pkt[udp_start..udp_start + 2].copy_from_slice(&67u16.to_be_bytes());
    pkt[udp_start + 2..udp_start + 4].copy_from_slice(&68u16.to_be_bytes());
    pkt[udp_start + 4..udp_start + 6].copy_from_slice(&udp_len.to_be_bytes());
    let ip_total = (pkt.len() - ip_start) as u16;
    pkt[ip_start] = 0x45;
    pkt[ip_start + 2..ip_start + 4].copy_from_slice(&ip_total.to_be_bytes());
    pkt[ip_start + 6] = 0x40;
    pkt[ip_start + 8] = 64;
    pkt[ip_start + 9] = 17;
    pkt[ip_start + 12..ip_start + 16].copy_from_slice(&GW_IP);
    pkt[ip_start + 16..ip_start + 20].copy_from_slice(&BROADCAST_IP);
    let cksum = ipv4_checksum(&pkt[ip_start..ip_start + 20]);
    pkt[ip_start + 10..ip_start + 12].copy_from_slice(&cksum.to_be_bytes());

    let mut frame = vec![0u8; VIRTIO_NET_HDR_SIZE];
    frame.extend_from_slice(&pkt);
    io.reply_queue.push_back(frame);
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn push_data_frames(c: &mut ProxyConn, data: &[u8], mac: &[u8; 6], ring: &SpscRing<256>) {
    let mut off = 0;
    while off < data.len() {
        let chunk = (data.len() - off).min(1460);
        let frame = build_tcp_frame(
            mac, GW_IP, VM_IP, c.src_port, 80,
            c.my_seq, c.peer_ack, 0x18, &data[off..off + chunk],
        );
        c.my_seq = c.my_seq.wrapping_add(chunk as u32);
        off += chunk;
        ring.push(&frame);
    }
}

fn build_grat_arp(guest_mac: &[u8; 6]) -> Vec<u8> {
    let mut arp = Vec::with_capacity(VIRTIO_NET_HDR_SIZE + 14 + 28);
    arp.extend_from_slice(&[0u8; VIRTIO_NET_HDR_SIZE]);
    arp.extend_from_slice(&[0xff; 6]);
    arp.extend_from_slice(&GW_MAC);
    arp.extend_from_slice(&0x0806u16.to_be_bytes());
    arp.extend_from_slice(&1u16.to_be_bytes());
    arp.extend_from_slice(&0x0800u16.to_be_bytes());
    arp.push(6); arp.push(4);
    arp.extend_from_slice(&2u16.to_be_bytes());
    arp.extend_from_slice(&GW_MAC);
    arp.extend_from_slice(&GW_IP);
    arp.extend_from_slice(guest_mac);
    arp.extend_from_slice(&GW_IP);
    arp
}

fn build_tcp_frame(
    dst_mac: &[u8; 6], src_ip: [u8; 4], dst_ip: [u8; 4],
    src_port: u16, dst_port: u16, seq: u32, ack: u32,
    flags: u8, payload: &[u8],
) -> Vec<u8> {
    let tcp_len = 20 + payload.len();
    let ip_total = 20 + tcp_len;
    let mut pkt = Vec::with_capacity(VIRTIO_NET_HDR_SIZE + 14 + ip_total);

    pkt.extend_from_slice(&[0u8; VIRTIO_NET_HDR_SIZE]);
    pkt.extend_from_slice(dst_mac);
    pkt.extend_from_slice(&GW_MAC);
    pkt.extend_from_slice(&0x0800u16.to_be_bytes());

    let ip_start = pkt.len();
    pkt.push(0x45); pkt.push(0);
    pkt.extend_from_slice(&(ip_total as u16).to_be_bytes());
    pkt.extend_from_slice(&[0, 0, 0x40, 0]);
    pkt.push(64); pkt.push(6);
    pkt.extend_from_slice(&[0, 0]);
    pkt.extend_from_slice(&src_ip);
    pkt.extend_from_slice(&dst_ip);
    let cksum = ipv4_checksum(&pkt[ip_start..ip_start + 20]);
    pkt[ip_start + 10] = (cksum >> 8) as u8;
    pkt[ip_start + 11] = (cksum & 0xff) as u8;

    let tcp_start = pkt.len();
    pkt.extend_from_slice(&src_port.to_be_bytes());
    pkt.extend_from_slice(&dst_port.to_be_bytes());
    pkt.extend_from_slice(&seq.to_be_bytes());
    pkt.extend_from_slice(&ack.to_be_bytes());
    pkt.push(0x50); pkt.push(flags);
    pkt.extend_from_slice(&0xffffu16.to_be_bytes());
    pkt.extend_from_slice(&[0, 0, 0, 0]);
    pkt.extend_from_slice(payload);
    let tcp_cksum = tcp_checksum(&src_ip, &dst_ip, &pkt[tcp_start..]);
    pkt[tcp_start + 16] = (tcp_cksum >> 8) as u8;
    pkt[tcp_start + 17] = (tcp_cksum & 0xff) as u8;

    pkt
}

fn ipv4_checksum(hdr: &[u8]) -> u16 {
    let mut s: u32 = 0;
    let mut i = 0;
    while i + 1 < hdr.len() { s += ((hdr[i] as u32) << 8) | hdr[i+1] as u32; i += 2; }
    if i < hdr.len() { s += (hdr[i] as u32) << 8; }
    while s >> 16 != 0 { s = (s & 0xffff) + (s >> 16); }
    !(s as u16)
}

fn tcp_checksum(src_ip: &[u8; 4], dst_ip: &[u8; 4], seg: &[u8]) -> u16 {
    let mut s: u32 = 0;
    s += ((src_ip[0] as u32) << 8) | src_ip[1] as u32;
    s += ((src_ip[2] as u32) << 8) | src_ip[3] as u32;
    s += ((dst_ip[0] as u32) << 8) | dst_ip[1] as u32;
    s += ((dst_ip[2] as u32) << 8) | dst_ip[3] as u32;
    s += 6;
    s += seg.len() as u32;
    let mut i = 0;
    while i + 1 < seg.len() { s += ((seg[i] as u32) << 8) | seg[i+1] as u32; i += 2; }
    if i < seg.len() { s += (seg[i] as u32) << 8; }
    while s >> 16 != 0 { s = (s & 0xffff) + (s >> 16); }
    !(s as u16)
}
