// tools/hvf-runner/src/userspace_net.rs
//
// Userspace TCP/IP proxy — zero-copy, no intermediate buffers.
//
// RX thread: poll() on sockets → construct frames directly in guest
//   RAM (virtio used ring) → assert SPI 35 to wake guest.
// vCPU thread: on TX QUEUE_NOTIFY → read frames from guest RAM →
//   write() directly to host sockets.
//
// No SPSC rings, no wake pipe, no Mutex on the hot path.

use std::collections::VecDeque;
use std::sync::{Mutex, OnceLock};

use crate::hvf;
use crate::virtio;

const VIRTIO_NET_HDR_SIZE: usize = 12;
const GW_MAC: [u8; 6] = [0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff];
const VM_IP: [u8; 4] = [10, 0, 2, 15];
const GW_IP: [u8; 4] = [10, 0, 2, 2];
const BROADCAST_IP: [u8; 4] = [255, 255, 255, 255];

/// Protocol for a user-specified port forward.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Proto {
    Tcp,
    Udp,
}

/// A single `host:guest` forward rule, either TCP or UDP.
///
/// The CLI parses `-p tcp:H:G` / `-p udp:H:G` into a `Vec<PortMapping>`
/// which is passed to `start()`. Multiple forwards of the same proto are
/// supported; each gets its own listen socket.
#[derive(Clone, Copy, Debug)]
pub struct PortMapping {
    pub proto: Proto,
    pub host: u16,
    pub guest: u16,
}

/// Fixed-size frame buffer — eliminates per-request heap allocation.
/// Covers all reply frame types: TCP ACK (66B), ARP (54B), DHCP (~400B).
const MAX_REPLY_FRAME: usize = 600;

#[derive(Clone, Copy)]
struct TxFrame {
    data: [u8; MAX_REPLY_FRAME],
    len: u16,
    queue_pair: u8,  // Which RX queue pair to inject into (Tier 1).
}

impl TxFrame {
    #[inline]
    fn as_slice(&self) -> &[u8] {
        &self.data[..self.len as usize]
    }
}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum ConnState {
    SynSent = 0,
    Established = 1,
    Closed = 2,
}

struct ProxyConn {
    host_fd: i32,
    src_port: u16,
    /// Guest-side listening port that this connection targets — used as
    /// the `dst_port` in every TCP frame we synthesize for the guest.
    /// Populated from the `PortMapping` the listen socket was created for.
    guest_port: u16,
    my_seq: u32,
    peer_ack: u32,
    state: ConnState,
    pending: Vec<u8>,
    queue_pair: usize,  // Which RX queue pair to inject into (Tier 1).
}

use std::collections::HashMap;
static CONNS: std::sync::LazyLock<Mutex<HashMap<u16, ProxyConn>>> =
    std::sync::LazyLock::new(|| Mutex::new(HashMap::new()));
// RX_LAST: tracked in IoState (IO thread only).
// TX_LAST: tracked as static in process_tx (vCPU thread only).
/// Reply frames generated by the vCPU thread (ARP, TCP ACK/handshake, DHCP).
/// The IO thread drains and injects these — avoids data race on the RX used ring.
/// Uses fixed-size TxFrame to avoid per-request heap allocation.
static TX_REPLIES: Mutex<VecDeque<TxFrame>> = Mutex::new(VecDeque::new());

/// UDP relay table: one host fd per guest UDP port, published once by
/// `start()` and read by the vCPU thread in `handle_udp`. `OnceLock`
/// guarantees the vCPU thread never observes a partially-initialized
/// table — `start()` fills it before spawning the io_thread, which
/// happens before the VM is created.
static UDP_RELAYS: OnceLock<Vec<(i32, u16)>> = OnceLock::new();

/// UDP return-path lookup: `(guest_port, client_ephemeral_port)` →
/// external client sockaddr. Keyed on `guest_port` as well as the client
/// port so two UDP forwards on different guest ports don't collide if a
/// client happens to use the same ephemeral port on both.
///
/// Written by the IO thread on each incoming datagram (right before
/// injecting the frame into the guest ring). Read by the vCPU thread
/// in `handle_udp` when the guest sends a reply.
static UDP_CLIENTS: Mutex<Option<HashMap<(u16, u16), libc::sockaddr_in>>> =
    Mutex::new(None);

const GUEST_MAC: [u8; 6] = [0x52, 0x54, 0x00, 0x12, 0x34, 0x56];

/// Per-listen-socket state.
#[derive(Clone, Copy)]
struct TcpListen {
    fd: i32,
    guest_port: u16,
}

/// Per-UDP-relay-socket state.
#[derive(Clone, Copy)]
struct UdpRelay {
    fd: i32,
    guest_port: u16,
}

struct IoState {
    /// All TCP listen sockets, one per `-p tcp:H:G` mapping.
    listens: Vec<TcpListen>,
    /// All UDP relay sockets, one per `-p udp:H:G` mapping.
    udps: Vec<UdpRelay>,
    next_port: u16,
    guest_mac: [u8; 6],
    read_buf: [u8; 2048],
    rx_last: u16,              // Legacy: single-queue RX last index
    rx_lasts: [u16; 8],        // Per-queue-pair RX last indices (Tier 1)
    cpu_count: usize,          // Number of vCPUs (= num_queue_pairs)
    pollfds: Vec<libc::pollfd>,
    /// Guest-visible ephemeral src_port for each `Conn`-slot pollfd.
    /// Indices `[0, fixed_slots)` map to listens/udps and are filled
    /// with 0 placeholders; only `[fixed_slots..]` entries are valid.
    conn_ports: Vec<u16>,
    frame_buf: [u8; 2048],
}

fn bind_listen(host_port: u16) -> Result<i32, String> {
    unsafe {
        let fd = libc::socket(libc::AF_INET, libc::SOCK_STREAM, 0);
        if fd < 0 { return Err(format!("tcp socket(): {}", std::io::Error::last_os_error())); }
        let one: i32 = 1;
        libc::setsockopt(fd, libc::SOL_SOCKET, libc::SO_REUSEADDR,
                         &one as *const _ as *const _, 4);
        let mut addr: libc::sockaddr_in = std::mem::zeroed();
        addr.sin_family = libc::AF_INET as u8;
        addr.sin_port = host_port.to_be();
        addr.sin_addr.s_addr = u32::from_be_bytes([127, 0, 0, 1]).to_be();
        if libc::bind(fd, &addr as *const _ as *const _, std::mem::size_of_val(&addr) as u32) < 0 {
            let e = std::io::Error::last_os_error();
            libc::close(fd);
            return Err(format!("tcp bind({host_port}): {e}"));
        }
        libc::listen(fd, 128);
        libc::fcntl(fd, libc::F_SETFL, libc::O_NONBLOCK);
        Ok(fd)
    }
}

fn bind_udp(host_port: u16) -> Result<i32, String> {
    unsafe {
        let fd = libc::socket(libc::AF_INET, libc::SOCK_DGRAM, 0);
        if fd < 0 { return Err(format!("udp socket(): {}", std::io::Error::last_os_error())); }
        let one: i32 = 1;
        libc::setsockopt(fd, libc::SOL_SOCKET, libc::SO_REUSEADDR,
                         &one as *const _ as *const _, 4);
        // Large socket buffers absorb bursty high-concurrency udp_async
        // loads without dropping at the host kernel. 16 MiB on each side
        // is a no-cost sizing on macOS/Linux and keeps the bottleneck in
        // the guest's event loop rather than in our queue.
        let bufsz: i32 = 16 * 1024 * 1024;
        libc::setsockopt(fd, libc::SOL_SOCKET, libc::SO_RCVBUF,
                         &bufsz as *const _ as *const _, 4);
        libc::setsockopt(fd, libc::SOL_SOCKET, libc::SO_SNDBUF,
                         &bufsz as *const _ as *const _, 4);
        let mut addr: libc::sockaddr_in = std::mem::zeroed();
        addr.sin_family = libc::AF_INET as u8;
        addr.sin_port = host_port.to_be();
        addr.sin_addr.s_addr = u32::from_be_bytes([127, 0, 0, 1]).to_be();
        if libc::bind(fd, &addr as *const _ as *const _, std::mem::size_of_val(&addr) as u32) < 0 {
            let e = std::io::Error::last_os_error();
            libc::close(fd);
            return Err(format!("udp bind({host_port}): {e}"));
        }
        libc::fcntl(fd, libc::F_SETFL, libc::O_NONBLOCK);
        Ok(fd)
    }
}

pub fn start(mappings: &[PortMapping]) -> Result<[u8; 6], String> {
    let mac: [u8; 6] = GUEST_MAC;

    let mut listens: Vec<TcpListen> = Vec::new();
    let mut udps: Vec<UdpRelay> = Vec::new();
    for m in mappings {
        match m.proto {
            Proto::Tcp => {
                let fd = bind_listen(m.host)?;
                listens.push(TcpListen { fd, guest_port: m.guest });
            }
            Proto::Udp => match bind_udp(m.host) {
                Ok(fd) => udps.push(UdpRelay { fd, guest_port: m.guest }),
                // UDP bind is non-fatal — keep TCP working even if UDP port is taken.
                Err(e) => eprintln!("  warning: {e}"),
            },
        }
    }

    if !udps.is_empty() {
        let table: Vec<(i32, u16)> = udps.iter().map(|u| (u.fd, u.guest_port)).collect();
        UDP_RELAYS.set(table).ok();
        *UDP_CLIENTS.lock().unwrap() = Some(HashMap::new());
    }

    let listens_for_thread = listens.clone();
    let udps_for_thread = udps.clone();
    std::thread::spawn(move || { io_thread(listens_for_thread, udps_for_thread, mac); });

    eprintln!();
    eprintln!("  VM network: 10.0.2.15 (userspace, zero-copy)");
    for m in mappings.iter().filter(|m| m.proto == Proto::Tcp) {
        eprintln!("  TCP relay:  localhost:{} -> guest:{}", m.host, m.guest);
    }
    for m in mappings.iter().filter(|m| m.proto == Proto::Udp) {
        eprintln!("  UDP relay:  localhost:{} -> guest:{}", m.host, m.guest);
    }
    if let Some(first_tcp) = mappings.iter().find(|m| m.proto == Proto::Tcp) {
        eprintln!("  Benchmark:  wrk -t1 -c1 -d10s http://localhost:{}/health", first_tcp.host);
    }
    eprintln!();
    Ok(mac)
}

/// TX QUEUE_NOTIFY handler. Uses TX QueueSnapshot for lock-free guest
/// RAM access. Only takes DEVICE lock briefly for interrupt_status.
/// Accepts the queue index (odd = TX queue) to support multi-queue.
pub fn process_tx_queue(queue_idx: u32) {
    use std::cell::Cell;
    thread_local! {
        static TX_LAST_MAP: Cell<[u16; 9]> = const { Cell::new([0u16; 9]) };
    }
    let tx = virtio::queue_snapshot(queue_idx as usize);
    if !tx.ready { return; }

    // Map queue_idx to a slot in the per-thread last array (TX queues: 1,3,5,7,... → slots 0..8)
    let slot = (queue_idx / 2) as usize;
    if slot >= 9 { return; }

    let avail_idx = unsafe {
        core::ptr::read_volatile(tx.gpa_to_host(tx.avail_addr + 2) as *const u16)
    };
    let mut lasts = TX_LAST_MAP.with(|c| c.get());
    let mut last = lasts[slot];
    if last == avail_idx { return; }

    while last != avail_idx {
        let ring_idx = last & (tx.qsize - 1);
        let desc_idx = unsafe {
            core::ptr::read_volatile(
                tx.gpa_to_host(tx.avail_addr + 4 + ring_idx as u64 * 2) as *const u16)
        };
        let (addr, len) = unsafe {
            let dp = tx.gpa_to_host(tx.desc_addr + desc_idx as u64 * 16);
            (core::ptr::read_unaligned(dp as *const u64),
             core::ptr::read_unaligned(dp.add(8) as *const u32) as usize)
        };
        if len > VIRTIO_NET_HDR_SIZE {
            let frame = unsafe {
                std::slice::from_raw_parts(
                    tx.gpa_to_host(addr).add(VIRTIO_NET_HDR_SIZE),
                    len - VIRTIO_NET_HDR_SIZE)
            };
            handle_guest_tx(frame);
        }
        // Update TX used ring (host-side tracking via TX_LAST).
        let used_idx = last; // host tracks its own used_idx, not guest RAM
        unsafe {
            let entry = tx.gpa_to_host(tx.used_addr + 4 + (used_idx & (tx.qsize - 1)) as u64 * 8);
            core::ptr::write_unaligned(entry as *mut u32, desc_idx as u32);
            core::ptr::write_unaligned(entry.add(4) as *mut u32, len as u32);
            core::ptr::write_volatile(tx.gpa_to_host(tx.used_addr + 2) as *mut u16,
                used_idx.wrapping_add(1));
        }
        last = last.wrapping_add(1);
    }
    lasts[slot] = last;
    TX_LAST_MAP.with(|c| c.set(lasts));
    unsafe { core::arch::asm!("dsb sy", options(nostack)); }
    // No SPI assert here — ACK frames queued in TX_REPLIES will be
    // injected by the IO thread, which asserts SPI after injection.
    // Asserting here caused a spurious interrupt (guest polls, finds
    // no new RX, wastes an MMIO exit).
}

/// Backward-compat wrapper for single-queue callers.
#[allow(dead_code)]
pub fn process_tx() {
    process_tx_queue(1);
}

// ── IO / RX thread ──────────────────────────────────────────────────────────

fn io_thread(listens: Vec<TcpListen>, udps: Vec<UdpRelay>, mac: [u8; 6]) {
    // Read cpu_count from the virtio device (= num_queue_pairs).
    // The device is created after the IO thread starts, so spin-wait
    // for it to appear.
    let cpu_count = loop {
        {
            let dev = virtio::DEVICE.lock().unwrap();
            if let Some(d) = dev.as_ref() {
                break d.num_queue_pairs as usize;
            }
        }
        std::thread::sleep(std::time::Duration::from_millis(10));
    };
    let mut io = IoState {
        listens, udps, next_port: 40000, guest_mac: mac,
        read_buf: [0u8; 2048], rx_last: 0,
        rx_lasts: [0u16; 8], cpu_count,
        pollfds: Vec::with_capacity(64), conn_ports: Vec::with_capacity(64),
        frame_buf: [0u8; 2048],
    };
    TX_REPLIES.lock().unwrap().push_back(build_grat_arp_frame(&mac));
    let mut cleanup_ctr: u32 = 0;

    let multi_queue = cpu_count > 1;

    loop {
        // ── Get the appropriate RX queue snapshot(s) ────────────────────
        let snap = virtio::rx_queue_snapshot(); // queue 0 (always valid)

        // ── Drain reply frames from vCPU thread ────────────────────────
        {
            let mut woken = [false; 8]; // track which cores need waking
            let mut any = false;
            let mut replies = TX_REPLIES.lock().unwrap();
            while let Some(f) = replies.pop_front() {
                let qp = if multi_queue { f.queue_pair as usize } else { 0 };
                let (qsnap, rlast) = if multi_queue && qp < cpu_count {
                    (virtio::queue_snapshot(qp * 2), &mut io.rx_lasts[qp])
                } else {
                    (snap, &mut io.rx_last)
                };
                if !qsnap.ready || !inject_frame(f.as_slice(), &qsnap, rlast) {
                    replies.push_front(f);
                    break;
                }
                if multi_queue { woken[qp] = true; }
                any = true;
            }
            drop(replies);
            if any {
                unsafe { core::arch::asm!("dsb sy", options(nostack)); }
                if multi_queue {
                    for qp in 0..cpu_count {
                        if woken[qp] { crate::vm::wake_vcpu(qp); }
                    }
                } else {
                    // Single-queue: wake the (only) vCPU (may be parked on
                    // cooperative-yield condvar) and deliver the virtio SPI.
                    crate::vm::wake_vcpu(0);
                    unsafe { hvf::hv_gic_set_spi(35, true); hvf::hv_gic_set_spi(35, false); }
                }
            }
        }

        // ── Flush pending data for connections that just became ESTABLISHED ──
        {
            let mut conns = CONNS.lock().unwrap();
            let mut woken = [false; 8];
            let mut flushed = false;
            for c in conns.values_mut() {
                if c.state == ConnState::Established && !c.pending.is_empty() {
                    let qp = if multi_queue { c.queue_pair } else { 0 };
                    let (qsnap, rlast) = if multi_queue && qp < cpu_count {
                        (virtio::queue_snapshot(qp * 2), &mut io.rx_lasts[qp])
                    } else {
                        (snap, &mut io.rx_last)
                    };
                    if qsnap.ready {
                        let p = std::mem::take(&mut c.pending);
                        inject_data_frames(c, &p, &GUEST_MAC, &qsnap, rlast, &mut io.frame_buf);
                        if multi_queue { woken[qp] = true; }
                        flushed = true;
                    }
                }
            }
            if flushed {
                unsafe { core::arch::asm!("dsb sy", options(nostack)); }
                if multi_queue {
                    for qp in 0..cpu_count {
                        if woken[qp] { crate::vm::wake_vcpu(qp); }
                    }
                } else {
                    crate::vm::wake_vcpu(0);
                    unsafe { hvf::hv_gic_set_spi(35, true); hvf::hv_gic_set_spi(35, false); }
                }
            }
        }

        // ── Build pollfds ──────────────────────────────────────────────
        // Layout (variable): N listens, M udp relays, then conn fds.
        // `conn_ports[i]` is the guest-visible ephemeral src_port for
        // slot i, and is only valid in the `[fixed_slots..]` range.
        let conns = CONNS.lock().unwrap();
        io.pollfds.clear();
        io.conn_ports.clear();
        for l in &io.listens {
            io.pollfds.push(libc::pollfd { fd: l.fd, events: libc::POLLIN, revents: 0 });
            io.conn_ports.push(0);
        }
        for u in &io.udps {
            io.pollfds.push(libc::pollfd { fd: u.fd, events: libc::POLLIN, revents: 0 });
            io.conn_ports.push(0);
        }
        let fixed_slots = io.pollfds.len(); // slots above this are conns
        for c in conns.values() {
            io.pollfds.push(libc::pollfd {
                fd: if c.host_fd >= 0 && c.state < ConnState::Closed { c.host_fd } else { -1 },
                events: libc::POLLIN, revents: 0,
            });
            io.conn_ports.push(c.src_port);
        }
        drop(conns);

        let ready = unsafe { libc::poll(io.pollfds.as_mut_ptr(), io.pollfds.len() as u32, 5) };
        if ready <= 0 { continue; }

        // Accept new TCP connections on any listen socket that fired.
        for i in 0..io.listens.len() {
            if io.pollfds[i].revents & libc::POLLIN != 0 {
                let gp = io.listens[i].guest_port;
                let fd = io.listens[i].fd;
                accept_connections(&mut io, &snap, fd, gp);
            }
        }
        // Drain UDP relays that fired. Each mapping has its own socket.
        let listens_count = io.listens.len();
        for j in 0..io.udps.len() {
            let idx = listens_count + j;
            if io.pollfds[idx].revents & libc::POLLIN != 0 && snap.ready {
                let fd = io.udps[j].fd;
                let gp = io.udps[j].guest_port;
                handle_udp_rx(&mut io, &snap, fd, gp);
            }
        }

        // ── Zero-copy RX: read() into guest RAM ───────────────────────
        const HDR_LEN: usize = VIRTIO_NET_HDR_SIZE + 14 + 20 + 20; // 66 bytes
        const MAX_PAYLOAD: usize = 1460;

        struct ConnSnap { port: u16, guest_port: u16, fd: i32, seq: u32, ack: u32, queue_pair: usize }
        let mut woken = [false; 8];
        let mut injected = false;

        let any_rx_ready = if multi_queue {
            // At least one queue pair must be ready.
            (0..cpu_count).any(|qp| virtio::queue_snapshot(qp * 2).ready)
        } else {
            snap.ready
        };

        if any_rx_ready {
            // Brief lock: snapshot ready connections. Skip the fixed-slot
            // entries (listens + UDP relays) at the head of pollfds — only
            // conn-section entries can produce RX data.
            let snaps: Vec<ConnSnap> = {
                let conns = CONNS.lock().unwrap();
                (fixed_slots..io.pollfds.len())
                    .filter(|&i| io.pollfds[i].revents & (libc::POLLIN | libc::POLLHUP) != 0)
                    .filter_map(|i| {
                        let port = io.conn_ports[i];
                        conns.get(&port).and_then(|c| {
                            if c.host_fd >= 0 && c.state == ConnState::Established {
                                Some(ConnSnap {
                                    port, guest_port: c.guest_port, fd: c.host_fd,
                                    seq: c.my_seq, ack: c.peer_ack, queue_pair: c.queue_pair,
                                })
                            } else { None }
                        })
                    })
                    .collect()
            };

            // Read directly into guest descriptor buffers (no lock held).
            struct RxResult { port: u16, seq_advance: u32, eof: bool, queue_pair: usize }
            let mut results: Vec<RxResult> = Vec::new();

            for cs in &snaps {
                let qp = if multi_queue { cs.queue_pair } else { 0 };
                let (qsnap, rlast) = if multi_queue && qp < cpu_count {
                    (virtio::queue_snapshot(qp * 2), &mut io.rx_lasts[qp])
                } else {
                    (snap, &mut io.rx_last)
                };
                if !qsnap.ready { continue; }

                let avail_idx = unsafe {
                    core::ptr::read_volatile(qsnap.gpa_to_host(qsnap.avail_addr + 2) as *const u16)
                };
                if *rlast == avail_idx { continue; } // ring full
                let ring_idx = *rlast & (qsnap.qsize - 1);
                let desc_idx = unsafe {
                    core::ptr::read_volatile(
                        qsnap.gpa_to_host(qsnap.avail_addr + 4 + ring_idx as u64 * 2) as *const u16)
                };
                let buf_addr = unsafe {
                    core::ptr::read_unaligned(
                        qsnap.gpa_to_host(qsnap.desc_addr + desc_idx as u64 * 16) as *const u64)
                };
                let guest_buf = qsnap.gpa_to_host(buf_addr);

                // read() payload directly into guest RAM.
                let payload_ptr = unsafe { guest_buf.add(HDR_LEN) };
                let n = unsafe { libc::read(cs.fd, payload_ptr as *mut _, MAX_PAYLOAD) };
                if n <= 0 {
                    if n == 0 { results.push(RxResult { port: cs.port, seq_advance: 0, eof: true, queue_pair: qp }); }
                    continue;
                }
                let payload_len = n as usize;

                // Write headers around the payload already in guest RAM.
                let total = write_tcp_frame_around_payload(
                    guest_buf, &GUEST_MAC, GW_IP, VM_IP,
                    cs.port, cs.guest_port, cs.seq, cs.ack, 0x18, payload_len);

                // Update used ring.
                let used_idx = *rlast;
                unsafe {
                    let entry = qsnap.gpa_to_host(qsnap.used_addr + 4 + (used_idx & (qsnap.qsize - 1)) as u64 * 8);
                    core::ptr::write_unaligned(entry as *mut u32, desc_idx as u32);
                    core::ptr::write_unaligned(entry.add(4) as *mut u32, total as u32);
                    core::ptr::write_volatile(qsnap.gpa_to_host(qsnap.used_addr + 2) as *mut u16,
                        used_idx.wrapping_add(1));
                }
                *rlast = rlast.wrapping_add(1);
                if multi_queue {
                    woken[qp] = true;
                    if qp > 0 {
                        // Debug: verify secondary queue injection
                        let new_used = unsafe {
                            core::ptr::read_volatile(qsnap.gpa_to_host(qsnap.used_addr + 2) as *const u16)
                        };
                        eprintln!("  IO: injected qp={qp} qi={} used_idx={new_used} avail_idx={avail_idx}", qp * 2);
                    }
                }
                results.push(RxResult { port: cs.port, seq_advance: payload_len as u32, eof: false, queue_pair: qp });
                injected = true;
            }

            // Brief lock: update seq counters and handle EOFs.
            if !results.is_empty() {
                let mut conns = CONNS.lock().unwrap();
                for r in &results {
                    if let Some(c) = conns.get_mut(&r.port) {
                        if r.eof {
                            let frame = build_tcp_frame_fixed(&GUEST_MAC, GW_IP, VM_IP,
                                c.src_port, c.guest_port, c.my_seq, c.peer_ack, 0x11, &[]);
                            c.my_seq = c.my_seq.wrapping_add(1);
                            c.state = ConnState::Closed;
                            let qp = r.queue_pair;
                            let (qsnap, rlast) = if multi_queue && qp < cpu_count {
                                (virtio::queue_snapshot(qp * 2), &mut io.rx_lasts[qp])
                            } else {
                                (snap, &mut io.rx_last)
                            };
                            inject_frame(frame.as_slice(), &qsnap, rlast);
                            if multi_queue { woken[qp] = true; }
                            injected = true;
                        } else {
                            c.my_seq = c.my_seq.wrapping_add(r.seq_advance);
                        }
                    }
                }
            }
        } else {
            // RX queue not ready — buffer in pending.
            let mut conns = CONNS.lock().unwrap();
            for i in fixed_slots..io.pollfds.len() {
                if io.pollfds[i].revents & (libc::POLLIN | libc::POLLHUP) == 0 { continue; }
                let port = io.conn_ports[i];
                if let Some(c) = conns.get_mut(&port) {
                    if c.host_fd < 0 { continue; }
                    let n = unsafe {
                        libc::read(c.host_fd, io.read_buf.as_mut_ptr() as *mut _, io.read_buf.len())
                    };
                    if n > 0 { c.pending.extend_from_slice(&io.read_buf[..n as usize]); }
                }
            }
        }
        if injected {
            unsafe { core::arch::asm!("dsb sy", options(nostack)); }
            if multi_queue {
                for qp in 0..cpu_count {
                    if woken[qp] { crate::vm::wake_vcpu(qp); }
                }
            } else {
                crate::vm::wake_vcpu(0);
                unsafe { hvf::hv_gic_set_spi(35, true); hvf::hv_gic_set_spi(35, false); }
            }
        }

        // Periodically clean up closed connections (state=2, host_fd=-1).
        cleanup_ctr = cleanup_ctr.wrapping_add(1);
        if cleanup_ctr % 1000 == 0 {
            let mut conns = CONNS.lock().unwrap();
            conns.retain(|_, c| c.state < ConnState::Closed || c.host_fd >= 0);
        }
    }
}

fn accept_connections(io: &mut IoState, snap: &virtio::QueueSnapshot,
                      listen_fd: i32, guest_port: u16) {
    let multi_queue = io.cpu_count > 1;
    loop {
        let client_fd = unsafe {
            libc::accept(listen_fd, std::ptr::null_mut(), std::ptr::null_mut())
        };
        if client_fd < 0 { break; }
        unsafe {
            libc::fcntl(client_fd, libc::F_SETFL, libc::O_NONBLOCK);
            let one: i32 = 1;
            libc::setsockopt(client_fd, libc::IPPROTO_TCP, libc::TCP_NODELAY,
                             &one as *const _ as *const _, 4);
        }
        let src_port = io.next_port;
        io.next_port = if io.next_port >= 59999 { 40000 } else { io.next_port + 1 };

        // Assign queue pair round-robin across cores.
        let qp = if multi_queue { src_port as usize % io.cpu_count } else { 0 };

        let frame = build_tcp_frame_fixed(&io.guest_mac, GW_IP, VM_IP,
            src_port, guest_port, 1000, 0, 0x02, &[]);
        let (qsnap, rlast) = if multi_queue && qp < io.cpu_count {
            (virtio::queue_snapshot(qp * 2), &mut io.rx_lasts[qp])
        } else {
            (*snap, &mut io.rx_last)
        };
        if qsnap.ready {
            inject_frame(frame.as_slice(), &qsnap, rlast);
            unsafe { core::arch::asm!("dsb sy", options(nostack)); }
            if multi_queue {
                crate::vm::wake_vcpu(qp);
            } else {
                crate::vm::wake_vcpu(0);
                unsafe { hvf::hv_gic_set_spi(35, true); hvf::hv_gic_set_spi(35, false); }
            }
        } else { TX_REPLIES.lock().unwrap().push_back(frame); }
        CONNS.lock().unwrap().insert(src_port, ProxyConn {
            host_fd: client_fd, src_port, guest_port,
            my_seq: 1001, peer_ack: 0,
            state: ConnState::SynSent, pending: Vec::new(),
            queue_pair: qp,
        });
    }
}

/// Handle incoming UDP datagrams from external clients → inject into guest RX ring.
///
/// Called once per UDP relay socket that fired POLLIN. `fd` is the host
/// socket and `guest_port` is the guest-side UDP port that this relay
/// targets (the `GUEST` in `-p udp:HOST:GUEST`). All injected frames
/// carry `dst_port = guest_port`.
fn handle_udp_rx(io: &mut IoState, snap: &virtio::QueueSnapshot, fd: i32, guest_port: u16) {
    // Drain everything the socket has queued and inject as many frames
    // as the RX ring can hold. Firing the GIC SPI is an `hv_gic_set_spi`
    // hypercall that costs microseconds; firing it per-packet at
    // 300k+ pkt/s burns the io_thread and starves the vCPU, so batch-
    // fire exactly once at the end.
    //
    // Critically, we also fire SPI if we pulled socket data but
    // couldn't inject (ring full). Under the NAPI idle pattern the
    // guest is HLTed on WFI waiting for the next SPI, and a full
    // ring means "the guest has more buffers to re-arm"; if we
    // stayed silent because we couldn't inject, guest + host would
    // deadlock — guest waiting for a wake, host waiting for buffers.
    // Firing SPI unblocks the guest so it can poll, drain, and
    // re-arm; the next io_thread round then injects successfully.
    let mut any_injected = false;
    let mut ring_full_pending = false;

    loop {
        let mut client_addr: libc::sockaddr_in = unsafe { std::mem::zeroed() };
        let mut addr_len: libc::socklen_t = std::mem::size_of::<libc::sockaddr_in>() as u32;
        let n = unsafe {
            libc::recvfrom(fd, io.read_buf.as_mut_ptr() as *mut _,
                io.read_buf.len(), 0,
                &mut client_addr as *mut _ as *mut libc::sockaddr,
                &mut addr_len)
        };
        if n <= 0 { break; }
        let payload_len = n as usize;

        let client_port = u16::from_be(client_addr.sin_port);

        // Register the sender → sockaddr mapping BEFORE inject_frame
        // publishes the packet into the guest ring. Otherwise the
        // guest (especially under busy-poll) can see the RX, process
        // it, and call handle_udp for the reply before we've updated
        // UDP_CLIENTS — handle_udp's lookup returns None and the reply
        // is silently dropped. Keyed on `(guest_port, client_port)` so
        // two UDP forwards on different guest ports never collide.
        {
            let mut guard = UDP_CLIENTS.lock().unwrap();
            if let Some(ref mut m) = *guard {
                m.insert((guest_port, client_port), client_addr);
            }
        }

        // Build Eth+IP+UDP frame wrapping the payload, inject into guest RX ring.
        let frame_len = build_udp_frame(&mut io.frame_buf, &io.guest_mac,
            GW_IP, VM_IP, client_port, guest_port,
            &io.read_buf[..payload_len]);
        if !inject_frame(&io.frame_buf[..frame_len], snap, &mut io.rx_last) {
            // Ring full — drop this packet but keep draining so the
            // socket buffer doesn't overflow (the kernel's drop is
            // worse than ours because it breaks poll()). We'll still
            // fire SPI at the end to kick the guest into catching up.
            ring_full_pending = true;
            continue;
        }
        any_injected = true;
    }

    if any_injected || ring_full_pending {
        unsafe { core::arch::asm!("dsb sy", options(nostack)); }
        crate::vm::wake_vcpu(0);
        unsafe {
            hvf::hv_gic_set_spi(35, true);
            hvf::hv_gic_set_spi(35, false);
        }
    }
}

fn inject_frame(frame: &[u8], snap: &virtio::QueueSnapshot, rx_last: &mut u16) -> bool {
    let avail_idx = unsafe {
        core::ptr::read_volatile(snap.gpa_to_host(snap.avail_addr + 2) as *const u16)
    };
    let last = *rx_last;
    if last == avail_idx { return false; }
    let ring_idx = last & (snap.qsize - 1);
    let desc_idx = unsafe {
        core::ptr::read_volatile(
            snap.gpa_to_host(snap.avail_addr + 4 + ring_idx as u64 * 2) as *const u16)
    };
    let addr = unsafe {
        core::ptr::read_unaligned(
            snap.gpa_to_host(snap.desc_addr + desc_idx as u64 * 16) as *const u64)
    };
    unsafe {
        core::ptr::copy_nonoverlapping(frame.as_ptr(), snap.gpa_to_host(addr), frame.len());
    }
    let used_idx = unsafe {
        core::ptr::read_volatile(snap.gpa_to_host(snap.used_addr + 2) as *const u16)
    };
    unsafe {
        let entry = snap.gpa_to_host(snap.used_addr + 4 + (used_idx & (snap.qsize - 1)) as u64 * 8);
        core::ptr::write_unaligned(entry as *mut u32, desc_idx as u32);
        core::ptr::write_unaligned(entry.add(4) as *mut u32, frame.len() as u32);
        core::ptr::write_volatile(snap.gpa_to_host(snap.used_addr + 2) as *mut u16,
            used_idx.wrapping_add(1));
        // Flush the cache line containing used->idx so the guest PE sees it.
        // Apple Silicon HVF should be cache-coherent, but empirically the
        // guest reads stale used->idx on secondary queues without this.
        let used_ptr = snap.gpa_to_host(snap.used_addr + 2);
        core::arch::asm!(
            "dc cvau, {addr}",
            "dsb sy",
            addr = in(reg) used_ptr,
            options(nostack),
        );
    }
    *rx_last = last.wrapping_add(1);
    true
}

fn inject_data_frames(c: &mut ProxyConn, data: &[u8], mac: &[u8; 6],
                      snap: &virtio::QueueSnapshot, rx_last: &mut u16,
                      frame_buf: &mut [u8; 2048]) {
    let mut off = 0;
    while off < data.len() {
        let chunk = (data.len() - off).min(1460);
        let len = write_tcp_frame(frame_buf, mac, GW_IP, VM_IP, c.src_port, c.guest_port,
            c.my_seq, c.peer_ack, 0x18, &data[off..off + chunk]);
        c.my_seq = c.my_seq.wrapping_add(chunk as u32);
        off += chunk;
        inject_frame(&frame_buf[..len], snap, rx_last);
    }
}


// ── Guest TX (vCPU thread) ──────────────────────────────────────────────────

fn handle_guest_tx(frame: &[u8]) {
    if frame.len() < 14 { return; }
    match u16::from_be_bytes([frame[12], frame[13]]) {
        0x0806 => handle_arp(&frame[14..]),
        0x0800 => handle_ipv4(&frame[14..]),
        _ => {}
    }
}

fn handle_arp(arp: &[u8]) {
    if arp.len() < 28 { return; }
    if u16::from_be_bytes([arp[6], arp[7]]) != 1 { return; }
    if arp[24..28] != GW_IP { return; }
    let guest_mac: [u8; 6] = arp[8..14].try_into().unwrap_or([0; 6]);
    let mut f = TxFrame { data: [0u8; MAX_REPLY_FRAME], len: 0, queue_pair: 0 };
    {
        let b = &mut f.data;
        let mut o = VIRTIO_NET_HDR_SIZE; // virtio-net hdr (zeroed)
        b[o..o+6].copy_from_slice(&guest_mac); o += 6;
        b[o..o+6].copy_from_slice(&GW_MAC); o += 6;
        b[o..o+2].copy_from_slice(&0x0806u16.to_be_bytes()); o += 2;
        b[o..o+2].copy_from_slice(&1u16.to_be_bytes()); o += 2;
        b[o..o+2].copy_from_slice(&0x0800u16.to_be_bytes()); o += 2;
        b[o] = 6; b[o+1] = 4; o += 2;
        b[o..o+2].copy_from_slice(&2u16.to_be_bytes()); o += 2;
        b[o..o+6].copy_from_slice(&GW_MAC); o += 6;
        b[o..o+4].copy_from_slice(&GW_IP); o += 4;
        b[o..o+6].copy_from_slice(&arp[8..14]); o += 6;
        b[o..o+4].copy_from_slice(&arp[14..18]); o += 4;
        f.len = o as u16;
    }
    TX_REPLIES.lock().unwrap().push_back(f);
}

fn handle_ipv4(ip: &[u8]) {
    if ip.len() < 20 { return; }
    let ihl = ((ip[0] & 0x0f) as usize) * 4;
    match ip[9] { 6 => handle_tcp(&ip[ihl..]), 17 => handle_udp(&ip[ihl..]), _ => {} }
}

fn handle_tcp(tcp: &[u8]) {
    if tcp.len() < 20 { return; }
    let src_port = u16::from_be_bytes([tcp[0], tcp[1]]);
    let dst_port = u16::from_be_bytes([tcp[2], tcp[3]]);
    let seq = u32::from_be_bytes([tcp[4], tcp[5], tcp[6], tcp[7]]);
    let data_offset = ((tcp[12] >> 4) as usize) * 4;
    let flags = tcp[13];
    let payload = if tcp.len() > data_offset { &tcp[data_offset..] } else { &[] };

    // Snapshot connection state under brief lock — don't hold across write().
    struct TxSnap { fd: i32, port: u16, guest_port: u16, seq: u32, ack: u32, state: ConnState, queue_pair: usize }
    let snap = {
        let mut conns = CONNS.lock().unwrap();
        if flags & 0x04 != 0 {
            if let Some(c) = conns.get_mut(&dst_port) {
                c.state = ConnState::Closed;
            }
            return;
        }
        let c = match conns.get_mut(&dst_port) {
            Some(c) => c, None => return,
        };
        let s = TxSnap {
            fd: c.host_fd, port: c.src_port, guest_port: c.guest_port,
            seq: c.my_seq, ack: c.peer_ack, state: c.state, queue_pair: c.queue_pair,
        };
        // Update state eagerly (before dropping lock).
        match c.state {
            ConnState::SynSent => {
                if flags & 0x12 == 0x12 {
                    c.peer_ack = seq.wrapping_add(1);
                    c.state = ConnState::Established;
                }
            }
            ConnState::Established => {
                if !payload.is_empty() {
                    c.peer_ack = seq.wrapping_add(payload.len() as u32);
                }
                if flags & 0x01 != 0 {
                    c.peer_ack = c.peer_ack.wrapping_add(1);
                    c.my_seq = c.my_seq.wrapping_add(1);
                    c.state = ConnState::Closed;
                    unsafe { libc::close(c.host_fd); }
                    c.host_fd = -1;
                }
            }
            _ => {}
        }
        s
    }; // CONNS lock released

    // write() outside both CONNS and TX_REPLIES locks — no contention.
    if snap.state == ConnState::Established && !payload.is_empty() {
        let mut written = 0usize;
        while written < payload.len() {
            let n = unsafe {
                libc::write(snap.fd,
                    payload.as_ptr().add(written) as *const _,
                    payload.len() - written)
            };
            if n <= 0 { break; }
            written += n as usize;
        }
    }

    // Brief lock: just push reply frames (no write() held).
    let mut replies = TX_REPLIES.lock().unwrap();
    match snap.state {
        ConnState::SynSent => {
            if flags & 0x12 == 0x12 {
                let ack = seq.wrapping_add(1);
                let mut f = build_tcp_frame_fixed(&GUEST_MAC, GW_IP, VM_IP,
                    snap.port, snap.guest_port, snap.seq, ack, 0x10, &[]);
                f.queue_pair = snap.queue_pair as u8;
                replies.push_back(f);
            }
        }
        ConnState::Established => {
            if !payload.is_empty() {
                let ack = seq.wrapping_add(payload.len() as u32);
                let mut f = build_tcp_frame_fixed(&GUEST_MAC, GW_IP, VM_IP,
                    snap.port, src_port, snap.seq, ack, 0x10, &[]);
                f.queue_pair = snap.queue_pair as u8;
                replies.push_back(f);
            }
            if flags & 0x01 != 0 {
                let ack = snap.ack.wrapping_add(1);
                let mut f = build_tcp_frame_fixed(&GUEST_MAC, GW_IP, VM_IP,
                    snap.port, src_port, snap.seq, ack, 0x11, &[]);
                f.queue_pair = snap.queue_pair as u8;
                replies.push_back(f);
            }
        }
        _ => {}
    }
}

fn handle_udp(udp: &[u8]) {
    if udp.len() < 8 { return; }
    let src_port = u16::from_be_bytes([udp[0], udp[1]]);
    let dst_port = u16::from_be_bytes([udp[2], udp[3]]);
    // DHCP: guest port 68 → server port 67.
    if src_port == 68 && dst_port == 67 {
        handle_dhcp(&udp[8..]);
        return;
    }
    // General UDP relay: guest → external client.
    //
    // The guest's frame has src_port=<guest-side listener> (matches the
    // GUEST in one of our `-p udp:HOST:GUEST` mappings) and
    // dst_port=<client ephemeral>. We look up the external sockaddr by
    // the `(src_port, dst_port)` pair and send via whichever host socket
    // handles `src_port`.
    let payload = &udp[8..];
    if payload.is_empty() { return; }
    let fd = match UDP_RELAYS.get() {
        Some(table) => match table.iter().find(|(_, gp)| *gp == src_port) {
            Some((fd, _)) => *fd,
            None => return,
        },
        None => return,
    };
    let client_addr = {
        let guard = UDP_CLIENTS.lock().unwrap();
        guard.as_ref().and_then(|m| m.get(&(src_port, dst_port)).copied())
    };
    if let Some(addr) = client_addr {
        unsafe {
            libc::sendto(fd, payload.as_ptr() as *const _, payload.len(),
                0, &addr as *const _ as *const libc::sockaddr,
                std::mem::size_of::<libc::sockaddr_in>() as u32);
        }
    }
}

fn handle_dhcp(bootp: &[u8]) {
    if bootp.len() < 240 { return; }
    let mut msg_type: u8 = 0;
    let mut i = 240;
    while i < bootp.len() {
        let opt = bootp[i];
        if opt == 255 { break; } if opt == 0 { i += 1; continue; }
        if i + 1 >= bootp.len() { break; }
        let len = bootp[i + 1] as usize;
        if i + 2 + len > bootp.len() { break; }
        if opt == 53 && len >= 1 { msg_type = bootp[i + 2]; }
        i += 2 + len;
    }
    if msg_type != 1 && msg_type != 3 { return; }
    let reply_type: u8 = if msg_type == 1 { 2 } else { 5 };
    let guest_mac: [u8; 6] = [0x52, 0x54, 0x00, 0x12, 0x34, 0x56];
    // Build DHCP reply directly in a TxFrame (cold path, boot only).
    let mut f = TxFrame { data: [0u8; MAX_REPLY_FRAME], len: 0, queue_pair: 0 };
    let b = &mut f.data;
    let mut o = VIRTIO_NET_HDR_SIZE; // skip virtio-net hdr (zeroed)
    b[o..o+6].fill(0xff); o += 6; b[o..o+6].copy_from_slice(&GW_MAC); o += 6;
    b[o..o+2].copy_from_slice(&0x0800u16.to_be_bytes()); o += 2;
    let ip_start = o; o += 20; // IP header (filled below)
    let udp_start = o; o += 8; // UDP header (filled below)
    let bp = o; o += 236; // BOOTP reply
    b[bp] = 2; b[bp+1] = 1; b[bp+2] = 6;
    b[bp+4..bp+8].copy_from_slice(&bootp[4..8]);
    b[bp+16..bp+20].copy_from_slice(&VM_IP); b[bp+20..bp+24].copy_from_slice(&GW_IP);
    b[bp+28..bp+34].copy_from_slice(&guest_mac);
    // DHCP options
    let opts: &[u8] = &[
        99,130,83,99, 53,1,reply_type,
        54,4,GW_IP[0],GW_IP[1],GW_IP[2],GW_IP[3],
        51,4,0,1,0x51,0x80, 1,4,255,255,255,0,
        3,4,GW_IP[0],GW_IP[1],GW_IP[2],GW_IP[3],
        6,4,10,0,2,3, 255,
    ];
    b[o..o+opts.len()].copy_from_slice(opts); o += opts.len();
    // Fill UDP header
    let ul = (o - udp_start) as u16;
    b[udp_start..udp_start+2].copy_from_slice(&67u16.to_be_bytes());
    b[udp_start+2..udp_start+4].copy_from_slice(&68u16.to_be_bytes());
    b[udp_start+4..udp_start+6].copy_from_slice(&ul.to_be_bytes());
    // Fill IP header
    let it = (o - ip_start) as u16;
    b[ip_start] = 0x45; b[ip_start+2..ip_start+4].copy_from_slice(&it.to_be_bytes());
    b[ip_start+6] = 0x40; b[ip_start+8] = 64; b[ip_start+9] = 17;
    b[ip_start+12..ip_start+16].copy_from_slice(&GW_IP);
    b[ip_start+16..ip_start+20].copy_from_slice(&BROADCAST_IP);
    let cs = ipv4_checksum(&b[ip_start..ip_start+20]);
    b[ip_start+10..ip_start+12].copy_from_slice(&cs.to_be_bytes());
    f.len = o as u16;
    TX_REPLIES.lock().unwrap().push_back(f);
}

// ── Packet construction ─────────────────────────────────────────────────────

fn build_grat_arp_frame(mac: &[u8; 6]) -> TxFrame {
    let mut f = TxFrame { data: [0u8; MAX_REPLY_FRAME], len: 0, queue_pair: 0 };
    let b = &mut f.data;
    let mut o = VIRTIO_NET_HDR_SIZE; // virtio-net hdr (zeroed)
    b[o..o+6].fill(0xff); o += 6;
    b[o..o+6].copy_from_slice(&GW_MAC); o += 6;
    b[o..o+2].copy_from_slice(&0x0806u16.to_be_bytes()); o += 2;
    b[o..o+2].copy_from_slice(&1u16.to_be_bytes()); o += 2;
    b[o..o+2].copy_from_slice(&0x0800u16.to_be_bytes()); o += 2;
    b[o] = 6; b[o+1] = 4; o += 2;
    b[o..o+2].copy_from_slice(&2u16.to_be_bytes()); o += 2;
    b[o..o+6].copy_from_slice(&GW_MAC); o += 6;
    b[o..o+4].copy_from_slice(&GW_IP); o += 4;
    b[o..o+6].copy_from_slice(mac); o += 6;
    b[o..o+4].copy_from_slice(&GW_IP); o += 4;
    f.len = o as u16;
    f
}

/// Write a TCP frame into `buf`. Returns the total frame length.
/// Header layout: [virtio_net_hdr 12B][Eth 14B][IP 20B][TCP 20B][payload]
fn write_tcp_frame(buf: &mut [u8], dst_mac: &[u8; 6], src_ip: [u8; 4], dst_ip: [u8; 4],
    src_port: u16, dst_port: u16, seq: u32, ack: u32,
    flags: u8, payload: &[u8]) -> usize {
    let tcp_len = 20 + payload.len();
    let ip_total = 20 + tcp_len;
    let total = VIRTIO_NET_HDR_SIZE + 14 + ip_total;
    debug_assert!(total <= buf.len());

    // Virtio-net header (12 zero bytes).
    buf[..VIRTIO_NET_HDR_SIZE].fill(0);
    let mut o = VIRTIO_NET_HDR_SIZE;

    // Ethernet header.
    buf[o..o+6].copy_from_slice(dst_mac); o += 6;
    buf[o..o+6].copy_from_slice(&GW_MAC); o += 6;
    buf[o..o+2].copy_from_slice(&0x0800u16.to_be_bytes()); o += 2;

    // IPv4 header.
    let is = o;
    buf[o] = 0x45; buf[o+1] = 0; o += 2;
    buf[o..o+2].copy_from_slice(&(ip_total as u16).to_be_bytes()); o += 2;
    buf[o..o+4].copy_from_slice(&[0,0,0x40,0]); o += 4;
    buf[o] = 64; buf[o+1] = 6; o += 2;
    buf[o..o+2].fill(0); o += 2; // checksum placeholder
    buf[o..o+4].copy_from_slice(&src_ip); o += 4;
    buf[o..o+4].copy_from_slice(&dst_ip); o += 4;
    let cs = ipv4_checksum(&buf[is..is+20]);
    buf[is+10] = (cs >> 8) as u8; buf[is+11] = (cs & 0xff) as u8;

    // TCP header.
    let ts = o;
    buf[o..o+2].copy_from_slice(&src_port.to_be_bytes()); o += 2;
    buf[o..o+2].copy_from_slice(&dst_port.to_be_bytes()); o += 2;
    buf[o..o+4].copy_from_slice(&seq.to_be_bytes()); o += 4;
    buf[o..o+4].copy_from_slice(&ack.to_be_bytes()); o += 4;
    buf[o] = 0x50; buf[o+1] = flags; o += 2;
    buf[o..o+2].copy_from_slice(&0xffffu16.to_be_bytes()); o += 2;
    buf[o..o+4].fill(0); o += 4; // checksum + urgent ptr
    buf[o..o+payload.len()].copy_from_slice(payload); o += payload.len();
    let tc = tcp_checksum(&src_ip, &dst_ip, &buf[ts..ts+tcp_len]);
    buf[ts+16] = (tc >> 8) as u8; buf[ts+17] = (tc & 0xff) as u8;

    total
}

/// Write TCP frame headers around payload already at buf[66..66+payload_len].
/// The payload was read() directly into guest RAM; we just write headers before it.
/// Returns total frame length.
fn write_tcp_frame_around_payload(buf: *mut u8, dst_mac: &[u8; 6],
    src_ip: [u8; 4], dst_ip: [u8; 4], src_port: u16, dst_port: u16,
    seq: u32, ack: u32, flags: u8, payload_len: usize) -> usize {
    let tcp_len = 20 + payload_len;
    let ip_total = 20 + tcp_len;
    let total = VIRTIO_NET_HDR_SIZE + 14 + ip_total;
    // Write into guest RAM via raw pointer (payload is already there).
    let b = unsafe { std::slice::from_raw_parts_mut(buf, VIRTIO_NET_HDR_SIZE + 14 + 20 + 20) };
    write_tcp_frame_headers(b, dst_mac, src_ip, dst_ip, src_port, dst_port,
        seq, ack, flags, ip_total, tcp_len);
    // Compute TCP checksum over header + payload.
    let tcp_start = VIRTIO_NET_HDR_SIZE + 14 + 20;
    let tcp_seg = unsafe { std::slice::from_raw_parts(buf.add(tcp_start), tcp_len) };
    let tc = tcp_checksum(&src_ip, &dst_ip, tcp_seg);
    unsafe {
        *buf.add(tcp_start + 16) = (tc >> 8) as u8;
        *buf.add(tcp_start + 17) = (tc & 0xff) as u8;
    }
    total
}

/// Write just the headers (virtio + eth + ip + tcp) into buf[..66].
/// Does NOT write payload (caller handles that). Sets checksum placeholders.
fn write_tcp_frame_headers(buf: &mut [u8], dst_mac: &[u8; 6],
    src_ip: [u8; 4], dst_ip: [u8; 4], src_port: u16, dst_port: u16,
    seq: u32, ack: u32, flags: u8, ip_total: usize, tcp_len: usize) {
    buf[..VIRTIO_NET_HDR_SIZE].fill(0);
    let mut o = VIRTIO_NET_HDR_SIZE;
    buf[o..o+6].copy_from_slice(dst_mac); o += 6;
    buf[o..o+6].copy_from_slice(&GW_MAC); o += 6;
    buf[o..o+2].copy_from_slice(&0x0800u16.to_be_bytes()); o += 2;
    let is = o;
    buf[o] = 0x45; buf[o+1] = 0; o += 2;
    buf[o..o+2].copy_from_slice(&(ip_total as u16).to_be_bytes()); o += 2;
    buf[o..o+4].copy_from_slice(&[0,0,0x40,0]); o += 4;
    buf[o] = 64; buf[o+1] = 6; o += 2;
    buf[o..o+2].fill(0); o += 2;
    buf[o..o+4].copy_from_slice(&src_ip); o += 4;
    buf[o..o+4].copy_from_slice(&dst_ip); o += 4;
    let cs = ipv4_checksum(&buf[is..is+20]);
    buf[is+10] = (cs >> 8) as u8; buf[is+11] = (cs & 0xff) as u8;
    let ts = o;
    buf[o..o+2].copy_from_slice(&src_port.to_be_bytes()); o += 2;
    buf[o..o+2].copy_from_slice(&dst_port.to_be_bytes()); o += 2;
    buf[o..o+4].copy_from_slice(&seq.to_be_bytes()); o += 4;
    buf[o..o+4].copy_from_slice(&ack.to_be_bytes()); o += 4;
    buf[o] = 0x50; buf[o+1] = flags; o += 2;
    buf[o..o+2].copy_from_slice(&0xffffu16.to_be_bytes()); o += 2;
    buf[o..o+4].fill(0); // checksum + urgent (filled later)
}

/// Fixed-size frame wrapper — no heap allocation.
fn build_tcp_frame_fixed(dst_mac: &[u8; 6], src_ip: [u8; 4], dst_ip: [u8; 4],
    src_port: u16, dst_port: u16, seq: u32, ack: u32,
    flags: u8, payload: &[u8]) -> TxFrame {
    let mut f = TxFrame { data: [0u8; MAX_REPLY_FRAME], len: 0, queue_pair: 0 };
    f.len = write_tcp_frame(&mut f.data, dst_mac, src_ip, dst_ip,
        src_port, dst_port, seq, ack, flags, payload) as u16;
    f
}

/// Build a UDP frame: [virtio_net_hdr 12B][Eth 14B][IP 20B][UDP 8B][payload].
/// Returns total frame length written into `buf`.
fn build_udp_frame(buf: &mut [u8], dst_mac: &[u8; 6],
    src_ip: [u8; 4], dst_ip: [u8; 4],
    src_port: u16, dst_port: u16, payload: &[u8]) -> usize {
    let udp_len = 8 + payload.len();
    let ip_total = 20 + udp_len;
    let total = VIRTIO_NET_HDR_SIZE + 14 + ip_total;
    debug_assert!(total <= buf.len());

    // Virtio-net header (12 zero bytes).
    buf[..VIRTIO_NET_HDR_SIZE].fill(0);
    let mut o = VIRTIO_NET_HDR_SIZE;

    // Ethernet header.
    buf[o..o+6].copy_from_slice(dst_mac); o += 6;
    buf[o..o+6].copy_from_slice(&GW_MAC); o += 6;
    buf[o..o+2].copy_from_slice(&0x0800u16.to_be_bytes()); o += 2;

    // IPv4 header.
    let is = o;
    buf[o] = 0x45; buf[o+1] = 0; o += 2;
    buf[o..o+2].copy_from_slice(&(ip_total as u16).to_be_bytes()); o += 2;
    buf[o..o+4].copy_from_slice(&[0,0,0x40,0]); o += 4; // id=0, DF, frag=0
    buf[o] = 64; buf[o+1] = 17; o += 2; // TTL=64, protocol=UDP
    buf[o..o+2].fill(0); o += 2; // checksum placeholder
    buf[o..o+4].copy_from_slice(&src_ip); o += 4;
    buf[o..o+4].copy_from_slice(&dst_ip); o += 4;
    let cs = ipv4_checksum(&buf[is..is+20]);
    buf[is+10] = (cs >> 8) as u8; buf[is+11] = (cs & 0xff) as u8;

    // UDP header.
    let us = o;
    buf[o..o+2].copy_from_slice(&src_port.to_be_bytes()); o += 2;
    buf[o..o+2].copy_from_slice(&dst_port.to_be_bytes()); o += 2;
    buf[o..o+2].copy_from_slice(&(udp_len as u16).to_be_bytes()); o += 2;
    buf[o..o+2].fill(0); o += 2; // checksum placeholder
    buf[o..o+payload.len()].copy_from_slice(payload); o += payload.len();
    let uc = udp_checksum(&src_ip, &dst_ip, &buf[us..us+udp_len]);
    buf[us+6] = (uc >> 8) as u8; buf[us+7] = (uc & 0xff) as u8;

    total
}

fn udp_checksum(si: &[u8; 4], di: &[u8; 4], seg: &[u8]) -> u16 {
    let mut s: u32 = 0;
    s += ((si[0] as u32)<<8)|si[1] as u32; s += ((si[2] as u32)<<8)|si[3] as u32;
    s += ((di[0] as u32)<<8)|di[1] as u32; s += ((di[2] as u32)<<8)|di[3] as u32;
    s += 17; // protocol = UDP
    s += seg.len() as u32;
    let mut i = 0;
    while i+1 < seg.len() { s += ((seg[i] as u32)<<8)|seg[i+1] as u32; i += 2; }
    if i < seg.len() { s += (seg[i] as u32) << 8; }
    while s >> 16 != 0 { s = (s & 0xffff) + (s >> 16); }
    let r = !(s as u16);
    // UDP checksum of 0x0000 is transmitted as 0xFFFF (RFC 768).
    if r == 0 { 0xffff } else { r }
}

fn ipv4_checksum(h: &[u8]) -> u16 {
    let mut s: u32 = 0; let mut i = 0;
    while i+1 < h.len() { s += ((h[i] as u32) << 8) | h[i+1] as u32; i += 2; }
    if i < h.len() { s += (h[i] as u32) << 8; }
    while s >> 16 != 0 { s = (s & 0xffff) + (s >> 16); } !(s as u16)
}

fn tcp_checksum(si: &[u8; 4], di: &[u8; 4], seg: &[u8]) -> u16 {
    let mut s: u32 = 0;
    s += ((si[0] as u32)<<8)|si[1] as u32; s += ((si[2] as u32)<<8)|si[3] as u32;
    s += ((di[0] as u32)<<8)|di[1] as u32; s += ((di[2] as u32)<<8)|di[3] as u32;
    s += 6; s += seg.len() as u32; let mut i = 0;
    while i+1 < seg.len() { s += ((seg[i] as u32)<<8)|seg[i+1] as u32; i += 2; }
    if i < seg.len() { s += (seg[i] as u32) << 8; }
    while s >> 16 != 0 { s = (s & 0xffff) + (s >> 16); } !(s as u16)
}
