// tools/hvf-runner/src/userspace_net.rs
//
// Userspace TCP/IP proxy: replaces vmnet.framework with in-process
// networking. Listens on localhost:PORT, bridges TCP to guest virtio-net.
//
// **Single-threaded hot path**: all socket I/O (accept, read, write)
// runs from the vCPU thread via non-blocking kqueue — zero cross-thread
// synchronization. This matches QEMU's architecture and eliminates
// Mutex overhead that capped throughput at ~6500 req/s.

use std::collections::VecDeque;

use crate::hvf;
use crate::virtio;

// ── Network constants ───────────────────────────────────────────────────────

const VIRTIO_NET_HDR_SIZE: usize = 12;
const GW_MAC: [u8; 6] = [0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff];
const VM_IP: [u8; 4] = [10, 0, 2, 15];
const GW_IP: [u8; 4] = [10, 0, 2, 2];
const BROADCAST_IP: [u8; 4] = [255, 255, 255, 255];

// ── Per-connection state ────────────────────────────────────────────────────

struct ProxyConn {
    host_fd: i32,
    src_port: u16,
    my_seq: u32,
    peer_ack: u32,
    state: u8, // 0=SYN_SENT, 1=ESTABLISHED, 2=CLOSED
    pending: Vec<u8>,
}

// ── Global state (vCPU thread only — no sync needed) ────────────────────────

struct NetState {
    listen_fd: i32,
    conns: Vec<ProxyConn>,
    next_port: u16,
    guest_mac: [u8; 6],
    rx_queue: VecDeque<Vec<u8>>,
    read_buf: [u8; 8192],
    /// Throttle counter — only poll sockets every N MMIO exits.
    /// Reduces wasted read() syscalls from 800K/sec to ~12K/sec.
    poll_counter: u32,
    /// Set after writing to a host socket (response sent to wrk).
    /// Forces an immediate poll on the next check_rx() to pick up
    /// wrk's next request without waiting for the throttle counter.
    poll_now: bool,
}

/// Poll sockets every this many MMIO exits when idle.
/// 64 exits × ~1.2µs/exit ≈ 77µs max added latency for new connections.
const POLL_INTERVAL: u32 = 64;

static mut NET: Option<NetState> = None;

// ── Public API ──────────────────────────────────────────────────────────────

/// Start userspace networking. Returns the guest MAC address.
/// Sets up the listen socket and kqueue. No threads spawned.
pub fn start(port: u16) -> Result<[u8; 6], String> {
    let mac = [0x52, 0x54, 0x00, 0x12, 0x34, 0x56];

    // Create listen socket with SO_REUSEADDR.
    let listen_fd = unsafe {
        let fd = libc::socket(libc::AF_INET, libc::SOCK_STREAM, 0);
        if fd < 0 { return Err("socket() failed".into()); }
        let one: i32 = 1;
        libc::setsockopt(fd, libc::SOL_SOCKET, libc::SO_REUSEADDR,
                         &one as *const _ as *const _, 4);
        let mut addr: libc::sockaddr_in = std::mem::zeroed();
        addr.sin_family = libc::AF_INET as u8;
        addr.sin_port = port.to_be();
        addr.sin_addr.s_addr = u32::from_be_bytes([127, 0, 0, 1]).to_be();
        if libc::bind(fd, &addr as *const _ as *const _, std::mem::size_of_val(&addr) as u32) < 0 {
            let e = std::io::Error::last_os_error();
            libc::close(fd);
            return Err(format!("bind({port}): {e}"));
        }
        libc::listen(fd, 128);
        libc::fcntl(fd, libc::F_SETFL, libc::O_NONBLOCK);
        fd
    };

    unsafe {
        NET = Some(NetState {
            listen_fd,
            conns: Vec::new(),
            next_port: 40000,
            guest_mac: mac,
            rx_queue: VecDeque::new(),
            read_buf: [0u8; 8192],
            poll_counter: 0,
            poll_now: false,
        });
    }

    eprintln!();
    eprintln!("  VM network: 10.0.2.15 (userspace, no vmnet)");
    eprintln!("  Benchmark:  wrk -t1 -c1 -d10s http://localhost:{port}/health");
    eprintln!();

    Ok(mac)
}

/// Poll host sockets + inject RX frames. Called from vCPU thread on every exit.
/// All socket I/O is non-blocking — zero cross-thread synchronization.
///
/// Throttled: socket polling only happens every POLL_INTERVAL exits or
/// immediately after sending a response (poll_now flag). This reduces
/// wasted read() syscalls from ~800K/sec to ~12K/sec.
pub fn check_rx() {
    let net = unsafe { match NET.as_mut() { Some(n) => n, None => return } };

    // Always inject queued frames (generated by process_tx).
    if !net.rx_queue.is_empty() {
        inject_rx_frames(net);
    }

    // Throttle socket polling: poll every exit while expecting data
    // (poll_now), throttle to every POLL_INTERVAL exits when idle.
    net.poll_counter += 1;
    if !net.poll_now && net.poll_counter < POLL_INTERVAL { return; }
    net.poll_counter = 0;
    // Don't clear poll_now here — clear it only after successful read.

    // 1. Non-blocking accept.
    loop {
        let client_fd = unsafe {
            libc::accept(net.listen_fd, std::ptr::null_mut(), std::ptr::null_mut())
        };
        if client_fd < 0 { break; }
        unsafe {
            libc::fcntl(client_fd, libc::F_SETFL, libc::O_NONBLOCK);
            let one: i32 = 1;
            libc::setsockopt(client_fd, libc::IPPROTO_TCP, libc::TCP_NODELAY,
                             &one as *const _ as *const _, 4);
        }
        let src_port = net.next_port;
        net.next_port = if net.next_port >= 59999 { 40000 } else { net.next_port + 1 };
        let frame = build_tcp_frame(
            &net.guest_mac, GW_IP, VM_IP,
            src_port, 80, 1000, 0, 0x02, &[],
        );
        net.rx_queue.push_back(frame);
        net.conns.push(ProxyConn {
            host_fd: client_fd, src_port, my_seq: 1001, peer_ack: 0,
            state: 0, pending: Vec::new(),
        });
        // New connection — poll immediately to pick up wrk's request
        // data that may already be in the kernel socket buffer.
        net.poll_now = true;
    }

    // 2. Non-blocking read from active connections.
    for i in 0..net.conns.len() {
        let fd = net.conns[i].host_fd;
        if fd < 0 { continue; }
        let n = unsafe {
            libc::read(fd, net.read_buf.as_mut_ptr() as *mut _, net.read_buf.len())
        };
        if n == 0 {
            if net.conns[i].state == 1 {
                let mac = net.guest_mac;
                let c = &mut net.conns[i];
                let frame = build_tcp_frame(
                    &mac, GW_IP, VM_IP, c.src_port, 80,
                    c.my_seq, c.peer_ack, 0x11, &[],
                );
                c.my_seq = c.my_seq.wrapping_add(1);
                c.state = 2;
                net.rx_queue.push_back(frame);
            }
        } else if n > 0 {
            net.poll_now = false; // Got data — stop busy-polling.
            let data = net.read_buf[..n as usize].to_vec();
            let mac = net.guest_mac;
            let c = &mut net.conns[i];
            if c.state == 1 {
                send_data_frames(c, &data, &mac, &mut net.rx_queue);
            } else {
                c.pending.extend_from_slice(&data);
            }
        }
    }

    // 3. Inject queued frames into guest RX ring.
    if !net.rx_queue.is_empty() {
        inject_rx_frames(net);
    }
}

/// Extract frames from guest TX ring and process them.
pub fn process_tx() {
    let mut dev_lock = virtio::DEVICE.lock().unwrap();
    let dev = match dev_lock.as_mut() {
        Some(d) => d,
        None => return,
    };

    let q = dev.queue(1);
    if !q.ready { return; }
    let desc_base = q.desc_addr();
    let avail_base = q.avail_addr();
    let used_base = q.used_addr();
    let qsize = q.num as u16;
    if qsize == 0 { return; }

    let avail_idx = unsafe {
        core::ptr::read_volatile(dev.gpa_to_host(avail_base + 2) as *const u16)
    };
    static TX_LAST: std::sync::atomic::AtomicU16 = std::sync::atomic::AtomicU16::new(0);
    let mut last = TX_LAST.load(std::sync::atomic::Ordering::Relaxed);

    let mut tx_frames: Vec<Vec<u8>> = Vec::new();
    while last != avail_idx {
        let ring_idx = last & (qsize - 1);
        let desc_idx = unsafe {
            core::ptr::read_volatile(
                dev.gpa_to_host(avail_base + 4 + ring_idx as u64 * 2) as *const u16
            )
        };
        let (addr, len) = unsafe {
            let dp = dev.gpa_to_host(desc_base + desc_idx as u64 * 16);
            (core::ptr::read_unaligned(dp as *const u64),
             core::ptr::read_unaligned(dp.add(8) as *const u32) as usize)
        };

        if len > VIRTIO_NET_HDR_SIZE {
            let frame = unsafe {
                let ptr = dev.gpa_to_host(addr).add(VIRTIO_NET_HDR_SIZE);
                std::slice::from_raw_parts(ptr, len - VIRTIO_NET_HDR_SIZE).to_vec()
            };
            tx_frames.push(frame);
        }

        let used_idx = unsafe {
            core::ptr::read_volatile(dev.gpa_to_host(used_base + 2) as *const u16)
        };
        unsafe {
            let entry = dev.gpa_to_host(used_base + 4 + (used_idx & (qsize - 1)) as u64 * 8);
            core::ptr::write_unaligned(entry as *mut u32, desc_idx as u32);
            core::ptr::write_unaligned(entry.add(4) as *mut u32, len as u32);
            core::ptr::write_volatile(
                dev.gpa_to_host(used_base + 2) as *mut u16,
                used_idx.wrapping_add(1),
            );
        }
        last = last.wrapping_add(1);
    }
    TX_LAST.store(last, std::sync::atomic::Ordering::Relaxed);

    dev.interrupt_status |= 1;
    unsafe { core::arch::asm!("dsb sy", options(nostack)); }
    drop(dev_lock);
    unsafe { hvf::hv_gic_set_spi(35, true); }

    // Process TX frames outside DEVICE lock.
    let net = unsafe { match NET.as_mut() { Some(n) => n, None => return } };
    for frame in &tx_frames {
        handle_guest_tx(frame, net);
    }
}

// ── Guest TX frame handling ─────────────────────────────────────────────────

fn handle_guest_tx(frame: &[u8], net: &mut NetState) {
    if frame.len() < 14 { return; }
    let ethertype = u16::from_be_bytes([frame[12], frame[13]]);

    // Learn guest MAC.
    net.guest_mac.copy_from_slice(&frame[6..12]);

    match ethertype {
        0x0806 => handle_arp(&frame[14..], net),
        0x0800 => handle_ipv4(&frame[14..], net),
        _ => {}
    }
}

fn handle_arp(arp: &[u8], net: &mut NetState) {
    if arp.len() < 28 { return; }
    if u16::from_be_bytes([arp[6], arp[7]]) != 1 { return; } // Request only
    if arp[24..28] != GW_IP { return; }

    let mut reply = Vec::with_capacity(14 + 28);
    reply.extend_from_slice(&net.guest_mac);
    reply.extend_from_slice(&GW_MAC);
    reply.extend_from_slice(&0x0806u16.to_be_bytes());
    reply.extend_from_slice(&1u16.to_be_bytes());
    reply.extend_from_slice(&0x0800u16.to_be_bytes());
    reply.push(6); reply.push(4);
    reply.extend_from_slice(&2u16.to_be_bytes());
    reply.extend_from_slice(&GW_MAC);
    reply.extend_from_slice(&GW_IP);
    reply.extend_from_slice(&arp[8..14]);
    reply.extend_from_slice(&arp[14..18]);

    let mut frame = vec![0u8; VIRTIO_NET_HDR_SIZE];
    frame.extend_from_slice(&reply);
    net.rx_queue.push_back(frame);
}

fn handle_ipv4(ip: &[u8], net: &mut NetState) {
    if ip.len() < 20 { return; }
    let ihl = ((ip[0] & 0x0f) as usize) * 4;
    match ip[9] {
        6 => handle_tcp(&ip[ihl..], net),
        17 => handle_udp(&ip[ihl..], net),
        _ => {}
    }
}

fn handle_tcp(tcp: &[u8], net: &mut NetState) {
    if tcp.len() < 20 { return; }
    let src_port = u16::from_be_bytes([tcp[0], tcp[1]]);
    let dst_port = u16::from_be_bytes([tcp[2], tcp[3]]);
    let seq = u32::from_be_bytes([tcp[4], tcp[5], tcp[6], tcp[7]]);
    let data_offset = ((tcp[12] >> 4) as usize) * 4;
    let flags = tcp[13];
    let payload = if tcp.len() > data_offset { &tcp[data_offset..] } else { &[] };

    // RST
    if flags & 0x04 != 0 {
        if let Some(idx) = net.conns.iter().position(|c| c.src_port == dst_port) {
            unsafe { libc::close(net.conns[idx].host_fd); }
            net.conns.swap_remove(idx);
        }
        return;
    }

    let mac = net.guest_mac;
    let c = match net.conns.iter_mut().find(|c| c.src_port == dst_port) {
        Some(c) => c,
        None => return,
    };

    match c.state {
        0 => {
            // SYN_SENT → expect SYN+ACK
            if flags & 0x12 == 0x12 {
                c.peer_ack = seq.wrapping_add(1);
                c.state = 1;
                let frame = build_tcp_frame(
                    &mac, GW_IP, VM_IP, c.src_port, 80,
                    c.my_seq, c.peer_ack, 0x10, &[],
                );
                net.rx_queue.push_back(frame);

                if !c.pending.is_empty() {
                    let pending = std::mem::take(&mut c.pending);
                    send_data_frames(c, &pending, &mac, &mut net.rx_queue);
                }
            }
        }
        1 => {
            if !payload.is_empty() {
                c.peer_ack = seq.wrapping_add(payload.len() as u32);
                // Forward to host socket — wrk will likely send next
                // request immediately, so set poll_now for fast pickup.
                unsafe {
                    libc::write(c.host_fd, payload.as_ptr() as *const _, payload.len());
                }
                net.poll_now = true;
                // ACK
                let frame = build_tcp_frame(
                    &mac, GW_IP, VM_IP, c.src_port, src_port,
                    c.my_seq, c.peer_ack, 0x10, &[],
                );
                net.rx_queue.push_back(frame);
            }
            if flags & 0x01 != 0 {
                c.peer_ack = c.peer_ack.wrapping_add(1);
                let frame = build_tcp_frame(
                    &mac, GW_IP, VM_IP, c.src_port, src_port,
                    c.my_seq, c.peer_ack, 0x11, &[],
                );
                c.my_seq = c.my_seq.wrapping_add(1);
                c.state = 2;
                net.rx_queue.push_back(frame);
                unsafe { libc::close(c.host_fd); }
                c.host_fd = -1;
            }
        }
        _ => {}
    }
}

fn handle_udp(udp: &[u8], net: &mut NetState) {
    if udp.len() < 8 { return; }
    let src_port = u16::from_be_bytes([udp[0], udp[1]]);
    let dst_port = u16::from_be_bytes([udp[2], udp[3]]);
    if src_port == 68 && dst_port == 67 {
        handle_dhcp(&udp[8..], net);
    }
}

fn handle_dhcp(bootp: &[u8], net: &mut NetState) {
    if bootp.len() < 240 { return; }
    let mut msg_type: u8 = 0;
    let mut i = 240;
    while i < bootp.len() {
        let opt = bootp[i];
        if opt == 255 { break; }
        if opt == 0 { i += 1; continue; }
        if i + 1 >= bootp.len() { break; }
        let len = bootp[i + 1] as usize;
        if i + 2 + len > bootp.len() { break; }
        if opt == 53 && len >= 1 { msg_type = bootp[i + 2]; }
        i += 2 + len;
    }
    if msg_type != 1 && msg_type != 3 { return; }
    let reply_type: u8 = if msg_type == 1 { 2 } else { 5 };

    let mut pkt = Vec::with_capacity(400);
    pkt.extend_from_slice(&[0xff; 6]);
    pkt.extend_from_slice(&GW_MAC);
    pkt.extend_from_slice(&0x0800u16.to_be_bytes());
    let ip_start = pkt.len();
    pkt.extend_from_slice(&[0u8; 20]);
    let udp_start = pkt.len();
    pkt.extend_from_slice(&[0u8; 8]);
    let bp_start = pkt.len();
    pkt.resize(bp_start + 236, 0);
    pkt[bp_start] = 2;
    pkt[bp_start + 1] = 1; pkt[bp_start + 2] = 6;
    pkt[bp_start + 4..bp_start + 8].copy_from_slice(&bootp[4..8]);
    pkt[bp_start + 16..bp_start + 20].copy_from_slice(&VM_IP);
    pkt[bp_start + 20..bp_start + 24].copy_from_slice(&GW_IP);
    pkt[bp_start + 28..bp_start + 34].copy_from_slice(&net.guest_mac);
    pkt.extend_from_slice(&[99, 130, 83, 99]);
    pkt.extend_from_slice(&[53, 1, reply_type]);
    pkt.extend_from_slice(&[54, 4]); pkt.extend_from_slice(&GW_IP);
    pkt.extend_from_slice(&[51, 4, 0, 1, 0x51, 0x80]);
    pkt.extend_from_slice(&[1, 4, 255, 255, 255, 0]);
    pkt.extend_from_slice(&[3, 4]); pkt.extend_from_slice(&GW_IP);
    pkt.extend_from_slice(&[6, 4, 10, 0, 2, 3]);
    pkt.push(255);

    let udp_len = (pkt.len() - udp_start) as u16;
    pkt[udp_start..udp_start + 2].copy_from_slice(&67u16.to_be_bytes());
    pkt[udp_start + 2..udp_start + 4].copy_from_slice(&68u16.to_be_bytes());
    pkt[udp_start + 4..udp_start + 6].copy_from_slice(&udp_len.to_be_bytes());
    let ip_total = (pkt.len() - ip_start) as u16;
    pkt[ip_start] = 0x45;
    pkt[ip_start + 2..ip_start + 4].copy_from_slice(&ip_total.to_be_bytes());
    pkt[ip_start + 6] = 0x40;
    pkt[ip_start + 8] = 64;
    pkt[ip_start + 9] = 17;
    pkt[ip_start + 12..ip_start + 16].copy_from_slice(&GW_IP);
    pkt[ip_start + 16..ip_start + 20].copy_from_slice(&BROADCAST_IP);
    let cksum = ipv4_checksum(&pkt[ip_start..ip_start + 20]);
    pkt[ip_start + 10..ip_start + 12].copy_from_slice(&cksum.to_be_bytes());

    let mut frame = vec![0u8; VIRTIO_NET_HDR_SIZE];
    frame.extend_from_slice(&pkt);
    net.rx_queue.push_back(frame);
}

// ── Frame injection into guest RX ring ──────────────────────────────────────

fn inject_rx_frames(net: &mut NetState) {
    static RX_LAST: std::sync::atomic::AtomicU16 = std::sync::atomic::AtomicU16::new(0);

    let mut dev_lock = virtio::DEVICE.lock().unwrap();
    let dev = match dev_lock.as_mut() {
        Some(d) => d,
        None => return,
    };
    let q = dev.queue(0);
    if !q.ready { return; }
    let desc_base = q.desc_addr();
    let avail_base = q.avail_addr();
    let used_base = q.used_addr();
    let qsize = q.num as u16;
    if qsize == 0 { return; }

    let mut injected = 0u32;
    while let Some(frame) = net.rx_queue.pop_front() {
        let avail_idx = unsafe {
            core::ptr::read_volatile(dev.gpa_to_host(avail_base + 2) as *const u16)
        };
        let last = RX_LAST.load(std::sync::atomic::Ordering::Relaxed);
        if last == avail_idx {
            net.rx_queue.push_front(frame);
            break;
        }
        let ring_idx = last & (qsize - 1);
        let desc_idx = unsafe {
            core::ptr::read_volatile(
                dev.gpa_to_host(avail_base + 4 + ring_idx as u64 * 2) as *const u16
            )
        };
        let addr = unsafe {
            core::ptr::read_unaligned(
                dev.gpa_to_host(desc_base + desc_idx as u64 * 16) as *const u64
            )
        };
        let n = frame.len();
        unsafe {
            core::ptr::copy_nonoverlapping(frame.as_ptr(), dev.gpa_to_host(addr), n);
        }
        let used_idx = unsafe {
            core::ptr::read_volatile(dev.gpa_to_host(used_base + 2) as *const u16)
        };
        unsafe {
            let entry = dev.gpa_to_host(used_base + 4 + (used_idx & (qsize - 1)) as u64 * 8);
            core::ptr::write_unaligned(entry as *mut u32, desc_idx as u32);
            core::ptr::write_unaligned(entry.add(4) as *mut u32, n as u32);
            core::ptr::write_volatile(
                dev.gpa_to_host(used_base + 2) as *mut u16,
                used_idx.wrapping_add(1),
            );
        }
        RX_LAST.store(last.wrapping_add(1), std::sync::atomic::Ordering::Relaxed);
        dev.used_idx[0] = used_idx.wrapping_add(1);
        dev.interrupt_status |= 1;
        injected += 1;
    }
    if injected > 0 {
        unsafe { core::arch::asm!("dsb sy", options(nostack)); }
        unsafe { hvf::hv_gic_set_spi(35, true); }
    }
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn send_data_frames(c: &mut ProxyConn, data: &[u8], mac: &[u8; 6], q: &mut VecDeque<Vec<u8>>) {
    let mut off = 0;
    while off < data.len() {
        let chunk = (data.len() - off).min(1460);
        let frame = build_tcp_frame(
            mac, GW_IP, VM_IP, c.src_port, 80,
            c.my_seq, c.peer_ack, 0x18, &data[off..off + chunk],
        );
        c.my_seq = c.my_seq.wrapping_add(chunk as u32);
        off += chunk;
        q.push_back(frame);
    }
}

fn build_tcp_frame(
    dst_mac: &[u8; 6], src_ip: [u8; 4], dst_ip: [u8; 4],
    src_port: u16, dst_port: u16, seq: u32, ack: u32,
    flags: u8, payload: &[u8],
) -> Vec<u8> {
    let tcp_len = 20 + payload.len();
    let ip_total = 20 + tcp_len;
    let mut pkt = Vec::with_capacity(VIRTIO_NET_HDR_SIZE + 14 + ip_total);

    pkt.extend_from_slice(&[0u8; VIRTIO_NET_HDR_SIZE]);
    pkt.extend_from_slice(dst_mac);
    pkt.extend_from_slice(&GW_MAC);
    pkt.extend_from_slice(&0x0800u16.to_be_bytes());

    let ip_start = pkt.len();
    pkt.push(0x45); pkt.push(0);
    pkt.extend_from_slice(&(ip_total as u16).to_be_bytes());
    pkt.extend_from_slice(&[0, 0, 0x40, 0]);
    pkt.push(64); pkt.push(6);
    pkt.extend_from_slice(&[0, 0]);
    pkt.extend_from_slice(&src_ip);
    pkt.extend_from_slice(&dst_ip);
    let cksum = ipv4_checksum(&pkt[ip_start..ip_start + 20]);
    pkt[ip_start + 10] = (cksum >> 8) as u8;
    pkt[ip_start + 11] = (cksum & 0xff) as u8;

    let tcp_start = pkt.len();
    pkt.extend_from_slice(&src_port.to_be_bytes());
    pkt.extend_from_slice(&dst_port.to_be_bytes());
    pkt.extend_from_slice(&seq.to_be_bytes());
    pkt.extend_from_slice(&ack.to_be_bytes());
    pkt.push(0x50); pkt.push(flags);
    pkt.extend_from_slice(&0xffffu16.to_be_bytes());
    pkt.extend_from_slice(&[0, 0, 0, 0]);
    pkt.extend_from_slice(payload);
    let tcp_cksum = tcp_checksum(&src_ip, &dst_ip, &pkt[tcp_start..]);
    pkt[tcp_start + 16] = (tcp_cksum >> 8) as u8;
    pkt[tcp_start + 17] = (tcp_cksum & 0xff) as u8;

    pkt
}

fn ipv4_checksum(hdr: &[u8]) -> u16 {
    let mut s: u32 = 0;
    let mut i = 0;
    while i + 1 < hdr.len() { s += ((hdr[i] as u32) << 8) | hdr[i+1] as u32; i += 2; }
    if i < hdr.len() { s += (hdr[i] as u32) << 8; }
    while s >> 16 != 0 { s = (s & 0xffff) + (s >> 16); }
    !(s as u16)
}

fn tcp_checksum(src_ip: &[u8; 4], dst_ip: &[u8; 4], seg: &[u8]) -> u16 {
    let mut s: u32 = 0;
    s += ((src_ip[0] as u32) << 8) | src_ip[1] as u32;
    s += ((src_ip[2] as u32) << 8) | src_ip[3] as u32;
    s += ((dst_ip[0] as u32) << 8) | dst_ip[1] as u32;
    s += ((dst_ip[2] as u32) << 8) | dst_ip[3] as u32;
    s += 6;
    s += seg.len() as u32;
    let mut i = 0;
    while i + 1 < seg.len() { s += ((seg[i] as u32) << 8) | seg[i+1] as u32; i += 2; }
    if i < seg.len() { s += (seg[i] as u32) << 8; }
    while s >> 16 != 0 { s = (s & 0xffff) + (s >> 16); }
    !(s as u16)
}
