load("@rules_rust//rust:defs.bzl", "rust_library")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("//bazel/rules:rust.bzl", "UNIKERNEL_RUSTC_FLAGS")
load("//bazel/rules:unikernel.bzl", "unikernel_binary")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "app",
    srcs = ["main.rs"],
    compile_data = [
        "//apps/webserver/dev_certs:dev_cert.der",
        "//apps/webserver/dev_certs:dev_key.der",
    ],
    rustc_flags = UNIKERNEL_RUSTC_FLAGS,
    deps = [
        "//kernel",
        "//uni",
        "//net:tls",
        "//net:tls_crypto",
        "@crates//:rustls",
        "@crates//:rustls-pki-types",
        "@crates//:rustls-rustcrypto",
    ],
)

unikernel_binary(
    name = "test_tls",
    app = ":app",
)

sh_test(
    name = "test",
    timeout = "long",
    srcs = ["test_tls.sh"],
    data = select({
        "//bazel/platforms:runner_qemu": [
            ":test_tls.elf",
            ":test_tls.img",
            "//scripts:helpers.sh",
        ],
        "//bazel/platforms:runner_hvf": [
            ":test_tls.img",
            "//tools/hvf-runner:run_hvf",
        ],
        "//conditions:default": [],
    }),
    tags = [
        "exclusive",
        "local",
    ],
)
