load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

package(default_visibility = ["//visibility:public"])

exports_files([
    "run-local.sh",
    "make-limine-iso.sh",
    "helpers.sh",
])

sh_binary(
    name = "make_limine_iso",
    srcs = ["make-limine-iso.sh"],
    data = ["//boot:limine.conf"],
)
