#!/usr/bin/env bash
# setup-dev.sh — Install all build/run dependencies on macOS
#
# Run this once before building or running the unikernel.

set -euo pipefail

echo "==> Checking for Homebrew..."
if ! command -v brew &>/dev/null; then
    echo "  Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "==> Installing LLVM (clang, ld.lld, llvm-ar, llvm-nm)..."
brew install llvm

echo "==> Installing rustup (host toolchain for cargo standalone builds)..."
if ! command -v rustup &>/dev/null; then
    brew install rustup
    rustup default stable 2>/dev/null || true
fi

LLVM_PREFIX="$(brew --prefix llvm)"
echo "  LLVM installed at: $LLVM_PREFIX"

# Add LLVM to PATH for the current session and permanently
export PATH="$LLVM_PREFIX/bin:$PATH"

echo "  clang:  $(clang --version | head -1)"
echo "  ld.lld: $(ld.lld --version | head -1)"

echo "==> Installing Bazelisk (Bazel version manager)..."
brew install bazelisk

# Bazelisk is a wrapper that downloads the correct Bazel version automatically.
# We pin the version via .bazelversion.
echo "==> Creating .bazelversion..."
echo "7.3.1" > /Users/jitudas/github.com/r2jitu/unikernel/.bazelversion

echo "==> Installing QEMU (for local VM testing)..."
brew install qemu

echo "==> Installing GRUB (for creating bootable ISO images)..."
# grub for x86_64 on macOS
brew install grub 2>/dev/null || echo "  (grub may not be available via Homebrew on ARM — using raw ELF boot instead)"

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Generate .bazelrc.local so that plain "bazel build / bazel run" uses the
# correct target architecture for this machine (no --config flag needed).
HOST_ARCH="$(uname -m)"
BAZELRC_LOCAL="${PROJECT_ROOT}/.bazelrc.local"

echo "==> Generating .bazelrc.local for host arch: ${HOST_ARCH}..."
if [ "$HOST_ARCH" = "arm64" ]; then
    cat > "$BAZELRC_LOCAL" <<'EOF'
# Generated by setup-dev.sh — do not commit
# Default: native macOS arm64 (fast iteration, no VM required)
build --platforms=//bazel/platforms:aarch64_macos
# config=native: native macOS arm64 POSIX binary
build:native --platforms=//bazel/platforms:aarch64_macos
# config=qemu: aarch64 unikernel via QEMU
build:qemu --platforms=//bazel/platforms:aarch64_unikernel
EOF
    echo "  → aarch64_macos set as default (Apple Silicon detected)"
else
    cat > "$BAZELRC_LOCAL" <<'EOF'
# Generated by setup-dev.sh — do not commit
# Default: x86_64 unikernel (set globally in .bazelrc)
# config=native: native Linux x86_64 POSIX binary
build:native --platforms=//bazel/platforms:x86_64_linux
# config=qemu: x86_64 unikernel via QEMU
build:qemu --platforms=//bazel/platforms:x86_64_unikernel
EOF
    echo "  → x86_64 unikernel remains default (Intel/AMD host detected)"
fi

echo ""
echo "========================================="
echo "  Setup complete!"
echo "========================================="
echo ""
echo "  Required: add LLVM to your PATH permanently."
echo "  Add this to your ~/.zshrc or ~/.bash_profile:"
echo ""
echo '    export PATH="'"$LLVM_PREFIX"'/bin:$PATH"'
echo ""
echo "  Build and run the example web server:"
echo ""
echo "    cd ${PROJECT_ROOT}"
echo "    bazel run //apps/webserver"
echo ""
echo "  Run tests:"
echo ""
echo "    bazel test //apps/webserver:test"
echo ""
echo "  Access at: http://localhost:8080/"
echo "========================================="
