#!/usr/bin/env bash
# setup-dev.sh — Install all build/run dependencies on macOS
#
# Run this once before building or running the unikernel.

set -euo pipefail

echo "==> Checking for Homebrew..."
if ! command -v brew &>/dev/null; then
    echo "  Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "==> Installing LLVM (clang, ld.lld, llvm-ar, llvm-nm)..."
brew install llvm

echo "==> Installing rustup (host toolchain for cargo standalone builds)..."
if ! command -v rustup &>/dev/null; then
    brew install rustup
    rustup default stable 2>/dev/null || true
fi

LLVM_PREFIX="$(brew --prefix llvm)"
echo "  LLVM installed at: $LLVM_PREFIX"

# Add LLVM to PATH for the current session and permanently
export PATH="$LLVM_PREFIX/bin:$PATH"

echo "  clang:  $(clang --version | head -1)"
echo "  ld.lld: $(ld.lld --version | head -1)"

echo "==> Installing Bazelisk (Bazel version manager)..."
brew install bazelisk

# Bazelisk reads `.bazelversion` in the project root to pick the
# bazel binary to launch. We don't overwrite it here — the file
# is checked into the repo and should track whatever version the
# code actually builds with. If the file is missing, a developer
# building for the first time will see a clear bazelisk error
# pointing them at it.

echo "==> Installing QEMU (for local VM testing)..."
brew install qemu

echo "==> Installing GRUB (for creating bootable ISO images)..."
# grub for x86_64 on macOS
brew install grub 2>/dev/null || echo "  (grub may not be available via Homebrew on ARM — using raw ELF boot instead)"

echo "==> Installing code formatters (used by scripts/format.sh, the pre-commit auto-formatter, and the pre-push build check)..."
# clang-format ships with the LLVM install above; rustfmt comes via rustup.
rustup component add rustfmt 2>/dev/null || true
brew install buildifier ruff shfmt

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "==> Installing git hooks (pre-commit autoformatter + pre-push build check)..."
# Point git at the versioned hooks directory, and let `git blame` skip
# the repo-wide format commit recorded in .git-blame-ignore-revs.
git -C "$PROJECT_ROOT" config core.hooksPath scripts/git-hooks
git -C "$PROJECT_ROOT" config blame.ignoreRevsFile .git-blame-ignore-revs

# Generate .bazelrc.local so that plain "bazel build / bazel run" uses the
# correct target architecture for this machine (no --config flag needed).
HOST_ARCH="$(uname -m)"
BAZELRC_LOCAL="${PROJECT_ROOT}/.bazelrc.local"

echo "==> Generating .bazelrc.local for host arch: ${HOST_ARCH}..."

# Detect stale `build:qemu` / `build:hvf` / `build:iso` / `build:native`
# lines carried over from pre-variant-migration checkouts. Those configs
# were removed from .bazelrc (runner is per-target now); leftover lines
# are benign to Bazel but confusing on inspection.
if [ -f "$BAZELRC_LOCAL" ] && grep -qE "^build:(qemu|hvf|iso|native) " "$BAZELRC_LOCAL"; then
    echo "  note: stale pre-variant-migration configs detected in" \
        "existing .bazelrc.local — regenerating from scratch."
fi

if [ "$HOST_ARCH" = "arm64" ]; then
    cat >"$BAZELRC_LOCAL" <<'EOF'
# Generated by setup-dev.sh — do not commit
# Default host platform: native macOS arm64 (fast iteration, no VM).
# Variant targets (:<app>_hvf / _iso / _qemu_<arch>) carry their own
# transitions, so the host-platform default doesn't constrain them.
build --platforms=//bazel/platforms:aarch64_macos
EOF
    echo "  → aarch64_macos set as default (Apple Silicon detected)"
else
    cat >"$BAZELRC_LOCAL" <<'EOF'
# Generated by setup-dev.sh — do not commit
# Default host platform: native Linux x86_64. Variant targets
# (:<app>_hvf / _iso / _qemu_<arch>) carry their own transitions
# so the host-platform default doesn't constrain them.
build --platforms=//bazel/platforms:x86_64_linux
EOF
    echo "  → x86_64 Linux set as default"
fi

echo ""
echo "========================================="
echo "  Setup complete!"
echo "========================================="
echo ""
echo "  Required: add LLVM to your PATH permanently."
echo "  Add this to your ~/.zshrc or ~/.bash_profile:"
echo ""
echo '    export PATH="'"$LLVM_PREFIX"'/bin:$PATH"'
echo ""
echo "  Build and run the example web server:"
echo ""
echo "    cd ${PROJECT_ROOT}"
echo "    bazel run //apps/webserver"
echo ""
echo "  Run tests:"
echo ""
echo "    bazel test //apps/webserver:test"
echo ""
echo "  Access at: http://localhost:8080/"
echo "========================================="
