#!/usr/bin/env bash
# setup-dev-linux.sh — Install build/run dependencies on Ubuntu/Debian Linux
#
# Tested on Oracle Cloud Ubuntu 22.04 (ARM64 / Ampere A1 and x86_64).
# Run once after cloning the repo on a new cloud instance.
#
# Usage:
#   ./scripts/setup-dev-linux.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOST_ARCH="$(uname -m)"  # aarch64 or x86_64

echo "==> Host arch: $HOST_ARCH"

# ── System packages ───────────────────────────────────────────────────────────
echo "==> Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y \
    clang lld llvm \
    qemu-system-arm qemu-system-x86 qemu-kvm \
    git curl bc

echo "  clang: $(clang --version | head -1)"
echo "  lld:   $(ld.lld --version | head -1)"

# ── KVM access ────────────────────────────────────────────────────────────────
if [ -e /dev/kvm ]; then
    if ! groups | grep -qw kvm; then
        sudo usermod -aG kvm "$USER"
        echo "  Added $USER to kvm group (run 'newgrp kvm' or re-login)"
    else
        echo "  KVM: /dev/kvm available, user already in kvm group"
    fi
else
    echo "  Warning: /dev/kvm not found — check that nested virtualization is enabled"
fi

# ── Bazelisk (installed as `bazel`) ───────────────────────────────────────────
BAZEL_BIN=/usr/local/bin/bazel
if ! command -v bazel &>/dev/null; then
    echo "==> Installing Bazelisk..."
    case "$HOST_ARCH" in
        aarch64) BAZEL_ARCH="arm64" ;;
        x86_64)  BAZEL_ARCH="amd64" ;;
        *) echo "Unknown arch: $HOST_ARCH"; exit 1 ;;
    esac
    sudo curl -fsSL \
        "https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${BAZEL_ARCH}" \
        -o "$BAZEL_BIN"
    sudo chmod +x "$BAZEL_BIN"
    echo "  Installed Bazelisk as /usr/local/bin/bazel"
else
    echo "  bazel: already installed"
fi

# ── .bazelrc.local ────────────────────────────────────────────────────────────
BAZELRC_LOCAL="${PROJECT_ROOT}/.bazelrc.local"
echo "==> Generating .bazelrc.local for $HOST_ARCH..."

case "$HOST_ARCH" in
    aarch64)
        cat > "$BAZELRC_LOCAL" <<'EOF'
# Generated by setup-dev-linux.sh — do not commit
# Default: aarch64 unikernel (run with QEMU+KVM on ARM64 Linux)
build --platforms=//bazel/platforms:aarch64_unikernel
# config=native: native Linux aarch64 POSIX binary
build:native --platforms=//bazel/platforms:aarch64_linux
# config=qemu: aarch64 unikernel via QEMU (KVM auto-detected from /dev/kvm)
build:qemu --platforms=//bazel/platforms:aarch64_unikernel
EOF
        echo "  → aarch64_unikernel set as default"
        ;;
    x86_64)
        cat > "$BAZELRC_LOCAL" <<'EOF'
# Generated by setup-dev-linux.sh — do not commit
# Default: x86_64 unikernel
build --platforms=//bazel/platforms:x86_64_unikernel
# config=native: native Linux x86_64 POSIX binary
build:native --platforms=//bazel/platforms:x86_64_linux
# config=qemu: x86_64 unikernel via QEMU (KVM auto-detected from /dev/kvm)
build:qemu --platforms=//bazel/platforms:x86_64_unikernel
EOF
        echo "  → x86_64_unikernel set as default"
        ;;
esac

# ── Oracle free-tier keep-alive ───────────────────────────────────────────────
# Oracle reclaims free-tier instances after ~7 days of inactivity.
# This cron job logs a heartbeat every 6 days to prevent that.
KEEPALIVE_SCRIPT="/usr/local/bin/oracle-keepalive"
sudo tee "$KEEPALIVE_SCRIPT" > /dev/null <<'KEEPALIVE'
#!/bin/bash
logger -t oracle-keepalive "keep-alive heartbeat"
KEEPALIVE
sudo chmod +x "$KEEPALIVE_SCRIPT"

if ! crontab -l 2>/dev/null | grep -q oracle-keepalive; then
    (crontab -l 2>/dev/null; echo "0 12 */6 * * $KEEPALIVE_SCRIPT") | crontab -
    echo "==> Keep-alive cron installed (runs every 6 days)"
fi

# ── Idle auto-stop ────────────────────────────────────────────────────────────
# Stops the instance when CPU is idle and no SSH sessions are active.
# Oracle free tier can be stopped freely; Oracle will restart it on demand.
IDLE_SCRIPT="/usr/local/bin/idle-shutdown"
sudo tee "$IDLE_SCRIPT" > /dev/null <<'IDLE'
#!/bin/bash
# Auto-stop after IDLE_MINUTES of low CPU with no active SSH sessions.
IDLE_MINUTES=30
CPU_THRESHOLD=5

cpu=$(top -bn2 -d1 | grep "Cpu(s)" | tail -1 | awk '{print 100 - $8}' 2>/dev/null || echo 0)
ssh_sessions=$(who | grep -c pts/ 2>/dev/null || echo 0)

if (( $(echo "$cpu < $CPU_THRESHOLD" | bc -l) )) && [ "$ssh_sessions" -eq 0 ]; then
    echo "$(date): idle (cpu=${cpu}%, sessions=${ssh_sessions}), shutting down" \
        | tee -a /var/log/idle-shutdown.log
    sudo shutdown -h now
fi
IDLE
sudo chmod +x "$IDLE_SCRIPT"

if ! crontab -l 2>/dev/null | grep -q idle-shutdown; then
    (crontab -l 2>/dev/null; echo "*/5 * * * * $IDLE_SCRIPT") | crontab -
    echo "==> Idle-shutdown cron installed (checks every 5 min, stops after 30 min idle)"
fi

echo ""
echo "========================================="
echo "  Setup complete!"
echo "========================================="
echo ""
echo "  If you just joined the kvm group, activate it:"
echo "    newgrp kvm"
echo ""
echo "  Build and run the webserver (KVM auto-detected):"
echo "    cd $PROJECT_ROOT"
echo "    bazel run //apps/webserver"
echo ""
echo "  Run tests:"
echo "    bazel test //apps/webserver:test_qemu"
echo "========================================="
